;;;; PromptFont by Yukari "Shinmera" Hafner, accessible at https://shinmera.com/promptfont
(defpackage #:org.shirakumo.fraf.promptfont (:use))
(in-package #:org.shirakumo.fraf.promptfont)

(cl:define-symbol-macro ascii-bang "!")
(cl:setf (cl:symbol-value 'ascii-bang) "!")
(cl:define-symbol-macro ascii-doublequote "\"")
(cl:setf (cl:symbol-value 'ascii-doublequote) "\"")
(cl:define-symbol-macro ascii-hash "#")
(cl:setf (cl:symbol-value 'ascii-hash) "#")
(cl:define-symbol-macro ascii-dollar "$")
(cl:setf (cl:symbol-value 'ascii-dollar) "$")
(cl:define-symbol-macro ascii-percent "%")
(cl:setf (cl:symbol-value 'ascii-percent) "%")
(cl:define-symbol-macro ascii-ampersand "&")
(cl:setf (cl:symbol-value 'ascii-ampersand) "&")
(cl:define-symbol-macro ascii-quote "'")
(cl:setf (cl:symbol-value 'ascii-quote) "'")
(cl:define-symbol-macro ascii-open-paren "(")
(cl:setf (cl:symbol-value 'ascii-open-paren) "(")
(cl:define-symbol-macro ascii-close-paren ")")
(cl:setf (cl:symbol-value 'ascii-close-paren) ")")
(cl:define-symbol-macro ascii-star "*")
(cl:setf (cl:symbol-value 'ascii-star) "*")
(cl:define-symbol-macro ascii-plus "+")
(cl:setf (cl:symbol-value 'ascii-plus) "+")
(cl:define-symbol-macro ascii-comma ",")
(cl:setf (cl:symbol-value 'ascii-comma) ",")
(cl:define-symbol-macro ascii-dash "-")
(cl:setf (cl:symbol-value 'ascii-dash) "-")
(cl:define-symbol-macro ascii-period ".")
(cl:setf (cl:symbol-value 'ascii-period) ".")
(cl:define-symbol-macro ascii-slash "/")
(cl:setf (cl:symbol-value 'ascii-slash) "/")
(cl:define-symbol-macro ascii-0 "0")
(cl:setf (cl:symbol-value 'ascii-0) "0")
(cl:define-symbol-macro ascii-1 "1")
(cl:setf (cl:symbol-value 'ascii-1) "1")
(cl:define-symbol-macro ascii-2 "2")
(cl:setf (cl:symbol-value 'ascii-2) "2")
(cl:define-symbol-macro ascii-3 "3")
(cl:setf (cl:symbol-value 'ascii-3) "3")
(cl:define-symbol-macro ascii-4 "4")
(cl:setf (cl:symbol-value 'ascii-4) "4")
(cl:define-symbol-macro ascii-5 "5")
(cl:setf (cl:symbol-value 'ascii-5) "5")
(cl:define-symbol-macro ascii-6 "6")
(cl:setf (cl:symbol-value 'ascii-6) "6")
(cl:define-symbol-macro ascii-7 "7")
(cl:setf (cl:symbol-value 'ascii-7) "7")
(cl:define-symbol-macro ascii-8 "8")
(cl:setf (cl:symbol-value 'ascii-8) "8")
(cl:define-symbol-macro ascii-9 "9")
(cl:setf (cl:symbol-value 'ascii-9) "9")
(cl:define-symbol-macro ascii-colon ":")
(cl:setf (cl:symbol-value 'ascii-colon) ":")
(cl:define-symbol-macro ascii-semicolon ";")
(cl:setf (cl:symbol-value 'ascii-semicolon) ";")
(cl:define-symbol-macro ascii-open-caret "<")
(cl:setf (cl:symbol-value 'ascii-open-caret) "<")
(cl:define-symbol-macro ascii-equals "=")
(cl:setf (cl:symbol-value 'ascii-equals) "=")
(cl:define-symbol-macro ascii-close-caret ">")
(cl:setf (cl:symbol-value 'ascii-close-caret) ">")
(cl:define-symbol-macro ascii-question "?")
(cl:setf (cl:symbol-value 'ascii-question) "?")
(cl:define-symbol-macro ascii-at "@")
(cl:setf (cl:symbol-value 'ascii-at) "@")
(cl:define-symbol-macro ascii-upper-a "A")
(cl:setf (cl:symbol-value 'ascii-upper-a) "A")
(cl:define-symbol-macro ascii-upper-b "B")
(cl:setf (cl:symbol-value 'ascii-upper-b) "B")
(cl:define-symbol-macro ascii-upper-c "C")
(cl:setf (cl:symbol-value 'ascii-upper-c) "C")
(cl:define-symbol-macro ascii-upper-d "D")
(cl:setf (cl:symbol-value 'ascii-upper-d) "D")
(cl:define-symbol-macro ascii-upper-e "E")
(cl:setf (cl:symbol-value 'ascii-upper-e) "E")
(cl:define-symbol-macro ascii-upper-f "F")
(cl:setf (cl:symbol-value 'ascii-upper-f) "F")
(cl:define-symbol-macro ascii-upper-g "G")
(cl:setf (cl:symbol-value 'ascii-upper-g) "G")
(cl:define-symbol-macro ascii-upper-h "H")
(cl:setf (cl:symbol-value 'ascii-upper-h) "H")
(cl:define-symbol-macro ascii-upper-i "I")
(cl:setf (cl:symbol-value 'ascii-upper-i) "I")
(cl:define-symbol-macro ascii-upper-j "J")
(cl:setf (cl:symbol-value 'ascii-upper-j) "J")
(cl:define-symbol-macro ascii-upper-k "K")
(cl:setf (cl:symbol-value 'ascii-upper-k) "K")
(cl:define-symbol-macro ascii-upper-l "L")
(cl:setf (cl:symbol-value 'ascii-upper-l) "L")
(cl:define-symbol-macro ascii-upper-m "M")
(cl:setf (cl:symbol-value 'ascii-upper-m) "M")
(cl:define-symbol-macro ascii-upper-n "N")
(cl:setf (cl:symbol-value 'ascii-upper-n) "N")
(cl:define-symbol-macro ascii-upper-o "O")
(cl:setf (cl:symbol-value 'ascii-upper-o) "O")
(cl:define-symbol-macro ascii-upper-p "P")
(cl:setf (cl:symbol-value 'ascii-upper-p) "P")
(cl:define-symbol-macro ascii-upper-q "Q")
(cl:setf (cl:symbol-value 'ascii-upper-q) "Q")
(cl:define-symbol-macro ascii-upper-r "R")
(cl:setf (cl:symbol-value 'ascii-upper-r) "R")
(cl:define-symbol-macro ascii-upper-s "S")
(cl:setf (cl:symbol-value 'ascii-upper-s) "S")
(cl:define-symbol-macro ascii-upper-t "T")
(cl:setf (cl:symbol-value 'ascii-upper-t) "T")
(cl:define-symbol-macro ascii-upper-u "U")
(cl:setf (cl:symbol-value 'ascii-upper-u) "U")
(cl:define-symbol-macro ascii-upper-v "V")
(cl:setf (cl:symbol-value 'ascii-upper-v) "V")
(cl:define-symbol-macro ascii-upper-w "W")
(cl:setf (cl:symbol-value 'ascii-upper-w) "W")
(cl:define-symbol-macro ascii-upper-x "X")
(cl:setf (cl:symbol-value 'ascii-upper-x) "X")
(cl:define-symbol-macro ascii-upper-y "Y")
(cl:setf (cl:symbol-value 'ascii-upper-y) "Y")
(cl:define-symbol-macro ascii-upper-z "Z")
(cl:setf (cl:symbol-value 'ascii-upper-z) "Z")
(cl:define-symbol-macro ascii-open-bracket "[")
(cl:setf (cl:symbol-value 'ascii-open-bracket) "[")
(cl:define-symbol-macro ascii-backslash "\\")
(cl:setf (cl:symbol-value 'ascii-backslash) "\\")
(cl:define-symbol-macro ascii-close-bracket "]")
(cl:setf (cl:symbol-value 'ascii-close-bracket) "]")
(cl:define-symbol-macro ascii-caret "^")
(cl:setf (cl:symbol-value 'ascii-caret) "^")
(cl:define-symbol-macro ascii-underscore "_")
(cl:setf (cl:symbol-value 'ascii-underscore) "_")
(cl:define-symbol-macro ascii-backtick "`")
(cl:setf (cl:symbol-value 'ascii-backtick) "`")
(cl:define-symbol-macro ascii-lower-a "a")
(cl:setf (cl:symbol-value 'ascii-lower-a) "a")
(cl:define-symbol-macro ascii-lower-b "b")
(cl:setf (cl:symbol-value 'ascii-lower-b) "b")
(cl:define-symbol-macro ascii-lower-c "c")
(cl:setf (cl:symbol-value 'ascii-lower-c) "c")
(cl:define-symbol-macro ascii-lower-d "d")
(cl:setf (cl:symbol-value 'ascii-lower-d) "d")
(cl:define-symbol-macro ascii-lower-e "e")
(cl:setf (cl:symbol-value 'ascii-lower-e) "e")
(cl:define-symbol-macro ascii-lower-f "f")
(cl:setf (cl:symbol-value 'ascii-lower-f) "f")
(cl:define-symbol-macro ascii-lower-g "g")
(cl:setf (cl:symbol-value 'ascii-lower-g) "g")
(cl:define-symbol-macro ascii-lower-h "h")
(cl:setf (cl:symbol-value 'ascii-lower-h) "h")
(cl:define-symbol-macro ascii-lower-i "i")
(cl:setf (cl:symbol-value 'ascii-lower-i) "i")
(cl:define-symbol-macro ascii-lower-j "j")
(cl:setf (cl:symbol-value 'ascii-lower-j) "j")
(cl:define-symbol-macro ascii-lower-k "k")
(cl:setf (cl:symbol-value 'ascii-lower-k) "k")
(cl:define-symbol-macro ascii-lower-l "l")
(cl:setf (cl:symbol-value 'ascii-lower-l) "l")
(cl:define-symbol-macro ascii-lower-m "m")
(cl:setf (cl:symbol-value 'ascii-lower-m) "m")
(cl:define-symbol-macro ascii-lower-n "n")
(cl:setf (cl:symbol-value 'ascii-lower-n) "n")
(cl:define-symbol-macro ascii-lower-o "o")
(cl:setf (cl:symbol-value 'ascii-lower-o) "o")
(cl:define-symbol-macro ascii-lower-p "p")
(cl:setf (cl:symbol-value 'ascii-lower-p) "p")
(cl:define-symbol-macro ascii-lower-q "q")
(cl:setf (cl:symbol-value 'ascii-lower-q) "q")
(cl:define-symbol-macro ascii-lower-r "r")
(cl:setf (cl:symbol-value 'ascii-lower-r) "r")
(cl:define-symbol-macro ascii-lower-s "s")
(cl:setf (cl:symbol-value 'ascii-lower-s) "s")
(cl:define-symbol-macro ascii-lower-t "t")
(cl:setf (cl:symbol-value 'ascii-lower-t) "t")
(cl:define-symbol-macro ascii-lower-u "u")
(cl:setf (cl:symbol-value 'ascii-lower-u) "u")
(cl:define-symbol-macro ascii-lower-v "v")
(cl:setf (cl:symbol-value 'ascii-lower-v) "v")
(cl:define-symbol-macro ascii-lower-w "w")
(cl:setf (cl:symbol-value 'ascii-lower-w) "w")
(cl:define-symbol-macro ascii-lower-x "x")
(cl:setf (cl:symbol-value 'ascii-lower-x) "x")
(cl:define-symbol-macro ascii-lower-y "y")
(cl:setf (cl:symbol-value 'ascii-lower-y) "y")
(cl:define-symbol-macro ascii-lower-z "z")
(cl:setf (cl:symbol-value 'ascii-lower-z) "z")
(cl:define-symbol-macro ascii-open-brace "{")
(cl:setf (cl:symbol-value 'ascii-open-brace) "{")
(cl:define-symbol-macro ascii-bar "|")
(cl:setf (cl:symbol-value 'ascii-bar) "|")
(cl:define-symbol-macro ascii-close-brace "}")
(cl:setf (cl:symbol-value 'ascii-close-brace) "}")
(cl:define-symbol-macro ascii-tilde "~")
(cl:setf (cl:symbol-value 'ascii-tilde) "~")
(cl:define-symbol-macro icon-arrow-left "←")
(cl:setf (cl:symbol-value 'icon-arrow-left) "←")
(cl:define-symbol-macro icon-arrow-up "↑")
(cl:setf (cl:symbol-value 'icon-arrow-up) "↑")
(cl:define-symbol-macro icon-arrow-right "→")
(cl:setf (cl:symbol-value 'icon-arrow-right) "→")
(cl:define-symbol-macro icon-arrow-down "↓")
(cl:setf (cl:symbol-value 'icon-arrow-down) "↓")
(cl:define-symbol-macro icon-exchange "↔")
(cl:setf (cl:symbol-value 'icon-exchange) "↔")
(cl:define-symbol-macro icon-reverse "↕")
(cl:setf (cl:symbol-value 'icon-reverse) "↕")
(cl:define-symbol-macro xbox-left-trigger "↖")
(cl:setf (cl:symbol-value 'xbox-left-trigger) "↖")
(cl:define-symbol-macro xbox-right-trigger "↗")
(cl:setf (cl:symbol-value 'xbox-right-trigger) "↗")
(cl:define-symbol-macro xbox-left-shoulder "↘")
(cl:setf (cl:symbol-value 'xbox-left-shoulder) "↘")
(cl:define-symbol-macro xbox-right-shoulder "↙")
(cl:setf (cl:symbol-value 'xbox-right-shoulder) "↙")
(cl:define-symbol-macro nintendo-left-trigger "↚")
(cl:setf (cl:symbol-value 'nintendo-left-trigger) "↚")
(cl:define-symbol-macro nintendo-right-trigger "↛")
(cl:setf (cl:symbol-value 'nintendo-right-trigger) "↛")
(cl:define-symbol-macro nintendo-left-shoulder "↜")
(cl:setf (cl:symbol-value 'nintendo-left-shoulder) "↜")
(cl:define-symbol-macro nintendo-right-shoulder "↝")
(cl:setf (cl:symbol-value 'nintendo-right-shoulder) "↝")
(cl:define-symbol-macro dpad-left "↞")
(cl:setf (cl:symbol-value 'dpad-left) "↞")
(cl:define-symbol-macro dpad-up "↟")
(cl:setf (cl:symbol-value 'dpad-up) "↟")
(cl:define-symbol-macro dpad-right "↠")
(cl:setf (cl:symbol-value 'dpad-right) "↠")
(cl:define-symbol-macro dpad-down "↡")
(cl:setf (cl:symbol-value 'dpad-down) "↡")
(cl:define-symbol-macro dpad-left-right "↢")
(cl:setf (cl:symbol-value 'dpad-left-right) "↢")
(cl:define-symbol-macro dpad-up-down "↣")
(cl:setf (cl:symbol-value 'dpad-up-down) "↣")
(cl:define-symbol-macro gamepad-x "↤")
(cl:setf (cl:symbol-value 'gamepad-x) "↤")
(cl:define-symbol-macro gamepad-y "↥")
(cl:setf (cl:symbol-value 'gamepad-y) "↥")
(cl:define-symbol-macro gamepad-b "↦")
(cl:setf (cl:symbol-value 'gamepad-b) "↦")
(cl:define-symbol-macro gamepad-a "↧")
(cl:setf (cl:symbol-value 'gamepad-a) "↧")
(cl:define-symbol-macro gamepad-buttons "↨")
(cl:setf (cl:symbol-value 'gamepad-buttons) "↨")
(cl:define-symbol-macro analog-l-clockwise "↩")
(cl:setf (cl:symbol-value 'analog-l-clockwise) "↩")
(cl:define-symbol-macro analog-l-counter "↪")
(cl:setf (cl:symbol-value 'analog-l-counter) "↪")
(cl:define-symbol-macro analog-r-clockwise "↫")
(cl:setf (cl:symbol-value 'analog-r-clockwise) "↫")
(cl:define-symbol-macro analog-r-counter "↬")
(cl:setf (cl:symbol-value 'analog-r-counter) "↬")
(cl:define-symbol-macro analog-lr-blockwise "↭")
(cl:setf (cl:symbol-value 'analog-lr-blockwise) "↭")
(cl:define-symbol-macro analog-lr-counter "↮")
(cl:setf (cl:symbol-value 'analog-lr-counter) "↮")
(cl:define-symbol-macro sony-left-shoulder "↰")
(cl:setf (cl:symbol-value 'sony-left-shoulder) "↰")
(cl:define-symbol-macro sony-right-shoulder "↱")
(cl:setf (cl:symbol-value 'sony-right-shoulder) "↱")
(cl:define-symbol-macro sony-left-trigger "↲")
(cl:setf (cl:symbol-value 'sony-left-trigger) "↲")
(cl:define-symbol-macro sony-right-trigger "↳")
(cl:setf (cl:symbol-value 'sony-right-trigger) "↳")
(cl:define-symbol-macro dpad-left-down "↴")
(cl:setf (cl:symbol-value 'dpad-left-down) "↴")
(cl:define-symbol-macro gamepad-up-right "↵")
(cl:setf (cl:symbol-value 'gamepad-up-right) "↵")
(cl:define-symbol-macro analog-clockwise "↶")
(cl:setf (cl:symbol-value 'analog-clockwise) "↶")
(cl:define-symbol-macro analog-counter "↷")
(cl:setf (cl:symbol-value 'analog-counter) "↷")
(cl:define-symbol-macro analog-stick-click "↸")
(cl:setf (cl:symbol-value 'analog-stick-click) "↸")
(cl:define-symbol-macro analog-click "↹")
(cl:setf (cl:symbol-value 'analog-click) "↹")
(cl:define-symbol-macro analog-l-click "↺")
(cl:setf (cl:symbol-value 'analog-l-click) "↺")
(cl:define-symbol-macro analog-r-click "↻")
(cl:setf (cl:symbol-value 'analog-r-click) "↻")
(cl:define-symbol-macro analog-l-left "↼")
(cl:setf (cl:symbol-value 'analog-l-left) "↼")
(cl:define-symbol-macro analog-r-left "↽")
(cl:setf (cl:symbol-value 'analog-r-left) "↽")
(cl:define-symbol-macro analog-l-up "↾")
(cl:setf (cl:symbol-value 'analog-l-up) "↾")
(cl:define-symbol-macro analog-r-up "↿")
(cl:setf (cl:symbol-value 'analog-r-up) "↿")
(cl:define-symbol-macro analog-l-right "⇀")
(cl:setf (cl:symbol-value 'analog-l-right) "⇀")
(cl:define-symbol-macro analog-r-right "⇁")
(cl:setf (cl:symbol-value 'analog-r-right) "⇁")
(cl:define-symbol-macro analog-l-down "⇂")
(cl:setf (cl:symbol-value 'analog-l-down) "⇂")
(cl:define-symbol-macro analog-r-down "⇃")
(cl:setf (cl:symbol-value 'analog-r-down) "⇃")
(cl:define-symbol-macro analog-l-left-right "⇄")
(cl:setf (cl:symbol-value 'analog-l-left-right) "⇄")
(cl:define-symbol-macro analog-l-up-down "⇅")
(cl:setf (cl:symbol-value 'analog-l-up-down) "⇅")
(cl:define-symbol-macro analog-r-left-right "⇆")
(cl:setf (cl:symbol-value 'analog-r-left-right) "⇆")
(cl:define-symbol-macro analog-left "⇇")
(cl:setf (cl:symbol-value 'analog-left) "⇇")
(cl:define-symbol-macro analog-up "⇈")
(cl:setf (cl:symbol-value 'analog-up) "⇈")
(cl:define-symbol-macro analog-right "⇉")
(cl:setf (cl:symbol-value 'analog-right) "⇉")
(cl:define-symbol-macro analog-down "⇊")
(cl:setf (cl:symbol-value 'analog-down) "⇊")
(cl:define-symbol-macro analog-l "⇋")
(cl:setf (cl:symbol-value 'analog-l) "⇋")
(cl:define-symbol-macro analog-r "⇌")
(cl:setf (cl:symbol-value 'analog-r) "⇌")
(cl:define-symbol-macro analog-stick "⇍")
(cl:setf (cl:symbol-value 'analog-stick) "⇍")
(cl:define-symbol-macro dpad "⇎")
(cl:setf (cl:symbol-value 'dpad) "⇎")
(cl:define-symbol-macro xbox-x "⇐")
(cl:setf (cl:symbol-value 'xbox-x) "⇐")
(cl:define-symbol-macro xbox-y "⇑")
(cl:setf (cl:symbol-value 'xbox-y) "⇑")
(cl:define-symbol-macro xbox-b "⇒")
(cl:setf (cl:symbol-value 'xbox-b) "⇒")
(cl:define-symbol-macro xbox-a "⇓")
(cl:setf (cl:symbol-value 'xbox-a) "⇓")
(cl:define-symbol-macro analog-left-right "⇔")
(cl:setf (cl:symbol-value 'analog-left-right) "⇔")
(cl:define-symbol-macro analog-up-down "⇕")
(cl:setf (cl:symbol-value 'analog-up-down) "⇕")
(cl:define-symbol-macro analog-up-left "⇖")
(cl:setf (cl:symbol-value 'analog-up-left) "⇖")
(cl:define-symbol-macro analog-up-right "⇗")
(cl:setf (cl:symbol-value 'analog-up-right) "⇗")
(cl:define-symbol-macro analog-down-right "⇘")
(cl:setf (cl:symbol-value 'analog-down-right) "⇘")
(cl:define-symbol-macro analog-down-left "⇙")
(cl:setf (cl:symbol-value 'analog-down-left) "⇙")
(cl:define-symbol-macro analog-l-touch "⇚")
(cl:setf (cl:symbol-value 'analog-l-touch) "⇚")
(cl:define-symbol-macro analog-r-touch "⇛")
(cl:setf (cl:symbol-value 'analog-r-touch) "⇛")
(cl:define-symbol-macro xbox-left-trigger-pull "⇜")
(cl:setf (cl:symbol-value 'xbox-left-trigger-pull) "⇜")
(cl:define-symbol-macro xbox-right-trigger-pull "⇝")
(cl:setf (cl:symbol-value 'xbox-right-trigger-pull) "⇝")
(cl:define-symbol-macro dpad-right-down "⇞")
(cl:setf (cl:symbol-value 'dpad-right-down) "⇞")
(cl:define-symbol-macro dupad-left-up "⇟")
(cl:setf (cl:symbol-value 'dupad-left-up) "⇟")
(cl:define-symbol-macro sony-x "⇠")
(cl:setf (cl:symbol-value 'sony-x) "⇠")
(cl:define-symbol-macro sony-y "⇡")
(cl:setf (cl:symbol-value 'sony-y) "⇡")
(cl:define-symbol-macro sony-b "⇢")
(cl:setf (cl:symbol-value 'sony-b) "⇢")
(cl:define-symbol-macro sony-a "⇣")
(cl:setf (cl:symbol-value 'sony-a) "⇣")
(cl:define-symbol-macro steam-menu "⇤")
(cl:setf (cl:symbol-value 'steam-menu) "⇤")
(cl:define-symbol-macro steam-options "⇥")
(cl:setf (cl:symbol-value 'steam-options) "⇥")
(cl:define-symbol-macro sony-share "⇦")
(cl:setf (cl:symbol-value 'sony-share) "⇦")
(cl:define-symbol-macro sony-touchpad "⇧")
(cl:setf (cl:symbol-value 'sony-touchpad) "⇧")
(cl:define-symbol-macro sony-options "⇨")
(cl:setf (cl:symbol-value 'sony-options) "⇨")
(cl:define-symbol-macro nintendo-button-z "⇩")
(cl:setf (cl:symbol-value 'nintendo-button-z) "⇩")
(cl:define-symbol-macro nintendo-trigger-z "⇪")
(cl:setf (cl:symbol-value 'nintendo-trigger-z) "⇪")
(cl:define-symbol-macro nintendo-c "⇫")
(cl:setf (cl:symbol-value 'nintendo-c) "⇫")
(cl:define-symbol-macro nintendo-z "⇬")
(cl:setf (cl:symbol-value 'nintendo-z) "⇬")
(cl:define-symbol-macro nintendo-1 "⇭")
(cl:setf (cl:symbol-value 'nintendo-1) "⇭")
(cl:define-symbol-macro nintendo-2 "⇮")
(cl:setf (cl:symbol-value 'nintendo-2) "⇮")
(cl:define-symbol-macro sony-left-stick "⇯")
(cl:setf (cl:symbol-value 'sony-left-stick) "⇯")
(cl:define-symbol-macro sony-right-stick "⇰")
(cl:setf (cl:symbol-value 'sony-right-stick) "⇰")
(cl:define-symbol-macro analog-l-any "⇱")
(cl:setf (cl:symbol-value 'analog-l-any) "⇱")
(cl:define-symbol-macro analog-r-any "⇲")
(cl:setf (cl:symbol-value 'analog-r-any) "⇲")
(cl:define-symbol-macro analog-any "⇳")
(cl:setf (cl:symbol-value 'analog-any) "⇳")
(cl:define-symbol-macro analog-r-up-down "⇵")
(cl:setf (cl:symbol-value 'analog-r-up-down) "⇵")
(cl:define-symbol-macro gamepad-select "⇷")
(cl:setf (cl:symbol-value 'gamepad-select) "⇷")
(cl:define-symbol-macro gamepad-start "⇸")
(cl:setf (cl:symbol-value 'gamepad-start) "⇸")
(cl:define-symbol-macro gamepad-home "⇹")
(cl:setf (cl:symbol-value 'gamepad-home) "⇹")
(cl:define-symbol-macro xbox-view "⇺")
(cl:setf (cl:symbol-value 'xbox-view) "⇺")
(cl:define-symbol-macro xbox-menu "⇻")
(cl:setf (cl:symbol-value 'xbox-menu) "⇻")
(cl:define-symbol-macro nintendo-minus "⇽")
(cl:setf (cl:symbol-value 'nintendo-minus) "⇽")
(cl:define-symbol-macro nintendo-plus "⇾")
(cl:setf (cl:symbol-value 'nintendo-plus) "⇾")
(cl:define-symbol-macro nintendo-dpad-left "⇿")
(cl:setf (cl:symbol-value 'nintendo-dpad-left) "⇿")
(cl:define-symbol-macro nintendo-dpad-up "∀")
(cl:setf (cl:symbol-value 'nintendo-dpad-up) "∀")
(cl:define-symbol-macro nintendo-dpad-right "∁")
(cl:setf (cl:symbol-value 'nintendo-dpad-right) "∁")
(cl:define-symbol-macro nintendo-dpad-down "∂")
(cl:setf (cl:symbol-value 'nintendo-dpad-down) "∂")
(cl:define-symbol-macro nintendo-joycon-sl "∃")
(cl:setf (cl:symbol-value 'nintendo-joycon-sl) "∃")
(cl:define-symbol-macro nintendo-joycon-sr "∄")
(cl:setf (cl:symbol-value 'nintendo-joycon-sr) "∄")
(cl:define-symbol-macro legion-settings "∅")
(cl:setf (cl:symbol-value 'legion-settings) "∅")
(cl:define-symbol-macro sony-dualsense-share "∆")
(cl:setf (cl:symbol-value 'sony-dualsense-share) "∆")
(cl:define-symbol-macro sony-dualsense-touchpad "∇")
(cl:setf (cl:symbol-value 'sony-dualsense-touchpad) "∇")
(cl:define-symbol-macro sony-dualsense-options "∈")
(cl:setf (cl:symbol-value 'sony-dualsense-options) "∈")
(cl:define-symbol-macro ayaneo-lc "∉")
(cl:setf (cl:symbol-value 'ayaneo-lc) "∉")
(cl:define-symbol-macro ayaneo-rc "∊")
(cl:setf (cl:symbol-value 'ayaneo-rc) "∊")
(cl:define-symbol-macro ayaneo-wave "∋")
(cl:setf (cl:symbol-value 'ayaneo-wave) "∋")
(cl:define-symbol-macro ayn-home "∌")
(cl:setf (cl:symbol-value 'ayn-home) "∌")
(cl:define-symbol-macro ayn-lcc "∍")
(cl:setf (cl:symbol-value 'ayn-lcc) "∍")
(cl:define-symbol-macro gpd-c1 "∎")
(cl:setf (cl:symbol-value 'gpd-c1) "∎")
(cl:define-symbol-macro gpd-c2 "∏")
(cl:setf (cl:symbol-value 'gpd-c2) "∏")
(cl:define-symbol-macro onexplayer-keyboard "∐")
(cl:setf (cl:symbol-value 'onexplayer-keyboard) "∐")
(cl:define-symbol-macro onexplayer-turbo "∑")
(cl:setf (cl:symbol-value 'onexplayer-turbo) "∑")
(cl:define-symbol-macro gamepad-m1 "−")
(cl:setf (cl:symbol-value 'gamepad-m1) "−")
(cl:define-symbol-macro gamepad-m2 "∓")
(cl:setf (cl:symbol-value 'gamepad-m2) "∓")
(cl:define-symbol-macro gamepad-m3 "∔")
(cl:setf (cl:symbol-value 'gamepad-m3) "∔")
(cl:define-symbol-macro gamepad-y1 "∕")
(cl:setf (cl:symbol-value 'gamepad-y1) "∕")
(cl:define-symbol-macro gamepad-y2 "∖")
(cl:setf (cl:symbol-value 'gamepad-y2) "∖")
(cl:define-symbol-macro gamepad-y3 "∗")
(cl:setf (cl:symbol-value 'gamepad-y3) "∗")
(cl:define-symbol-macro onexplayer-function "∘")
(cl:setf (cl:symbol-value 'onexplayer-function) "∘")
(cl:define-symbol-macro onexplayer-home "∙")
(cl:setf (cl:symbol-value 'onexplayer-home) "∙")
(cl:define-symbol-macro gpd-menu "√")
(cl:setf (cl:symbol-value 'gpd-menu) "√")
(cl:define-symbol-macro orangepi-controller "∛")
(cl:setf (cl:symbol-value 'orangepi-controller) "∛")
(cl:define-symbol-macro orangepi-home "∜")
(cl:setf (cl:symbol-value 'orangepi-home) "∜")
(cl:define-symbol-macro zotac-zone-logo "∝")
(cl:setf (cl:symbol-value 'zotac-zone-logo) "∝")
(cl:define-symbol-macro zotac-zone-menu "∞")
(cl:setf (cl:symbol-value 'zotac-zone-menu) "∞")
(cl:define-symbol-macro gamepad-x-b "∥")
(cl:setf (cl:symbol-value 'gamepad-x-b) "∥")
(cl:define-symbol-macro gamepad-a-y "∦")
(cl:setf (cl:symbol-value 'gamepad-a-y) "∦")
(cl:define-symbol-macro gamepad-x-y "∧")
(cl:setf (cl:symbol-value 'gamepad-x-y) "∧")
(cl:define-symbol-macro gamepad-b-y "∨")
(cl:setf (cl:symbol-value 'gamepad-b-y) "∨")
(cl:define-symbol-macro gamepad-a-b "∩")
(cl:setf (cl:symbol-value 'gamepad-a-b) "∩")
(cl:define-symbol-macro gamepad-x-a "∪")
(cl:setf (cl:symbol-value 'gamepad-x-a) "∪")
(cl:define-symbol-macro button-press "∫")
(cl:setf (cl:symbol-value 'button-press) "∫")
(cl:define-symbol-macro button-double-press "∬")
(cl:setf (cl:symbol-value 'button-double-press) "∬")
(cl:define-symbol-macro button-hold-press "∭")
(cl:setf (cl:symbol-value 'button-hold-press) "∭")
(cl:define-symbol-macro button-hold-release "∮")
(cl:setf (cl:symbol-value 'button-hold-release) "∮")
(cl:define-symbol-macro button-hold "∯")
(cl:setf (cl:symbol-value 'button-hold) "∯")
(cl:define-symbol-macro analog-fill "≊")
(cl:setf (cl:symbol-value 'analog-fill) "≊")
(cl:define-symbol-macro dpad-fill "≋")
(cl:setf (cl:symbol-value 'dpad-fill) "≋")
(cl:define-symbol-macro gamepad-fill "≌")
(cl:setf (cl:symbol-value 'gamepad-fill) "≌")
(cl:define-symbol-macro shoulder-fill "≍")
(cl:setf (cl:symbol-value 'shoulder-fill) "≍")
(cl:define-symbol-macro trigger-fill "≎")
(cl:setf (cl:symbol-value 'trigger-fill) "≎")
(cl:define-symbol-macro generic-fill "≏")
(cl:setf (cl:symbol-value 'generic-fill) "≏")
(cl:define-symbol-macro trackpad-l-any "≤")
(cl:setf (cl:symbol-value 'trackpad-l-any) "≤")
(cl:define-symbol-macro trackpad-r-any "≥")
(cl:setf (cl:symbol-value 'trackpad-r-any) "≥")
(cl:define-symbol-macro trackpad-l-click "≦")
(cl:setf (cl:symbol-value 'trackpad-l-click) "≦")
(cl:define-symbol-macro trackpad-r-click "≧")
(cl:setf (cl:symbol-value 'trackpad-r-click) "≧")
(cl:define-symbol-macro trackpad-l-touch "≨")
(cl:setf (cl:symbol-value 'trackpad-l-touch) "≨")
(cl:define-symbol-macro trackpad-r-touch "≩")
(cl:setf (cl:symbol-value 'trackpad-r-touch) "≩")
(cl:define-symbol-macro trackpad-l-left-right "≪")
(cl:setf (cl:symbol-value 'trackpad-l-left-right) "≪")
(cl:define-symbol-macro trackpad-l-up-down "≫")
(cl:setf (cl:symbol-value 'trackpad-l-up-down) "≫")
(cl:define-symbol-macro trackpad-r-left-right "≬")
(cl:setf (cl:symbol-value 'trackpad-r-left-right) "≬")
(cl:define-symbol-macro trackpad-r-up-down "≭")
(cl:setf (cl:symbol-value 'trackpad-r-up-down) "≭")
(cl:define-symbol-macro trackpad-l-left "≮")
(cl:setf (cl:symbol-value 'trackpad-l-left) "≮")
(cl:define-symbol-macro trackpad-r-left "≯")
(cl:setf (cl:symbol-value 'trackpad-r-left) "≯")
(cl:define-symbol-macro trackpad-l-up "≰")
(cl:setf (cl:symbol-value 'trackpad-l-up) "≰")
(cl:define-symbol-macro trackpad-r-up "≱")
(cl:setf (cl:symbol-value 'trackpad-r-up) "≱")
(cl:define-symbol-macro trackpad-l-right "≲")
(cl:setf (cl:symbol-value 'trackpad-l-right) "≲")
(cl:define-symbol-macro trackpad-r-right "≳")
(cl:setf (cl:symbol-value 'trackpad-r-right) "≳")
(cl:define-symbol-macro trackpad-l-down "≴")
(cl:setf (cl:symbol-value 'trackpad-l-down) "≴")
(cl:define-symbol-macro trackpad-r-down "≵")
(cl:setf (cl:symbol-value 'trackpad-r-down) "≵")
(cl:define-symbol-macro gamepad-l4 "≶")
(cl:setf (cl:symbol-value 'gamepad-l4) "≶")
(cl:define-symbol-macro gamepad-r4 "≷")
(cl:setf (cl:symbol-value 'gamepad-r4) "≷")
(cl:define-symbol-macro gamepad-l5 "≸")
(cl:setf (cl:symbol-value 'gamepad-l5) "≸")
(cl:define-symbol-macro gamepad-r5 "≹")
(cl:setf (cl:symbol-value 'gamepad-r5) "≹")
(cl:define-symbol-macro xbox-dpad-left "≺")
(cl:setf (cl:symbol-value 'xbox-dpad-left) "≺")
(cl:define-symbol-macro xbox-dpad-up "≻")
(cl:setf (cl:symbol-value 'xbox-dpad-up) "≻")
(cl:define-symbol-macro xbox-dpad-right "≼")
(cl:setf (cl:symbol-value 'xbox-dpad-right) "≼")
(cl:define-symbol-macro xbox-dpad-down "≽")
(cl:setf (cl:symbol-value 'xbox-dpad-down) "≽")
(cl:define-symbol-macro xbox-dpad-left-right "≾")
(cl:setf (cl:symbol-value 'xbox-dpad-left-right) "≾")
(cl:define-symbol-macro xbox-dpad-up-down "≿")
(cl:setf (cl:symbol-value 'xbox-dpad-up-down) "≿")
(cl:define-symbol-macro xbox-dpad-left-up "⊀")
(cl:setf (cl:symbol-value 'xbox-dpad-left-up) "⊀")
(cl:define-symbol-macro xbox-dpad-right-up "⊁")
(cl:setf (cl:symbol-value 'xbox-dpad-right-up) "⊁")
(cl:define-symbol-macro xbox-dpad-left-down "⊂")
(cl:setf (cl:symbol-value 'xbox-dpad-left-down) "⊂")
(cl:define-symbol-macro xbox-dpad-right-down "⊃")
(cl:setf (cl:symbol-value 'xbox-dpad-right-down) "⊃")
(cl:define-symbol-macro xbox-dpad "⊄")
(cl:setf (cl:symbol-value 'xbox-dpad) "⊄")
(cl:define-symbol-macro icon-pin "⌖")
(cl:setf (cl:symbol-value 'icon-pin) "⌖")
(cl:define-symbol-macro android-tabs "⏍")
(cl:setf (cl:symbol-value 'android-tabs) "⏍")
(cl:define-symbol-macro android-back "⏎")
(cl:setf (cl:symbol-value 'android-back) "⏎")
(cl:define-symbol-macro android-home "⏏")
(cl:setf (cl:symbol-value 'android-home) "⏏")
(cl:define-symbol-macro android-horizontal-dots "⏐")
(cl:setf (cl:symbol-value 'android-horizontal-dots) "⏐")
(cl:define-symbol-macro android-vertical-dots "⏑")
(cl:setf (cl:symbol-value 'android-vertical-dots) "⏑")
(cl:define-symbol-macro android-hamburger-menu "⏒")
(cl:setf (cl:symbol-value 'android-hamburger-menu) "⏒")
(cl:define-symbol-macro icon-fast-forward "⏩")
(cl:setf (cl:symbol-value 'icon-fast-forward) "⏩")
(cl:define-symbol-macro icon-rewind "⏪")
(cl:setf (cl:symbol-value 'icon-rewind) "⏪")
(cl:define-symbol-macro icon-play "⏬")
(cl:setf (cl:symbol-value 'icon-play) "⏬")
(cl:define-symbol-macro icon-skip-forward "⏭")
(cl:setf (cl:symbol-value 'icon-skip-forward) "⏭")
(cl:define-symbol-macro icon-skip-backward "⏮")
(cl:setf (cl:symbol-value 'icon-skip-backward) "⏮")
(cl:define-symbol-macro icon-play-pause "⏯")
(cl:setf (cl:symbol-value 'icon-play-pause) "⏯")
(cl:define-symbol-macro icon-hourglass "⏳")
(cl:setf (cl:symbol-value 'icon-hourglass) "⏳")
(cl:define-symbol-macro keyboard-left "⏴")
(cl:setf (cl:symbol-value 'keyboard-left) "⏴")
(cl:define-symbol-macro keyboard-right "⏵")
(cl:setf (cl:symbol-value 'keyboard-right) "⏵")
(cl:define-symbol-macro keyboard-up "⏶")
(cl:setf (cl:symbol-value 'keyboard-up) "⏶")
(cl:define-symbol-macro keyboard-down "⏷")
(cl:setf (cl:symbol-value 'keyboard-down) "⏷")
(cl:define-symbol-macro icon-pause "⏸")
(cl:setf (cl:symbol-value 'icon-pause) "⏸")
(cl:define-symbol-macro icon-stop "⏹")
(cl:setf (cl:symbol-value 'icon-stop) "⏹")
(cl:define-symbol-macro icon-record "⏺")
(cl:setf (cl:symbol-value 'icon-record) "⏺")
(cl:define-symbol-macro icon-power "⏻")
(cl:setf (cl:symbol-value 'icon-power) "⏻")
(cl:define-symbol-macro icon-power-toggle "⏼")
(cl:setf (cl:symbol-value 'icon-power-toggle) "⏼")
(cl:define-symbol-macro keyboard-84562 "␢")
(cl:setf (cl:symbol-value 'keyboard-84562) "␢")
(cl:define-symbol-macro keyboard-wasd "␣")
(cl:setf (cl:symbol-value 'keyboard-wasd) "␣")
(cl:define-symbol-macro keyboard-arrows "␤")
(cl:setf (cl:symbol-value 'keyboard-arrows) "␤")
(cl:define-symbol-macro keyboard-ijkl "␥")
(cl:setf (cl:symbol-value 'keyboard-ijkl) "␥")
(cl:define-symbol-macro keyboard-fn "␦")
(cl:setf (cl:symbol-value 'keyboard-fn) "␦")
(cl:define-symbol-macro keyboard-control "␧")
(cl:setf (cl:symbol-value 'keyboard-control) "␧")
(cl:define-symbol-macro keyboard-alt "␨")
(cl:setf (cl:symbol-value 'keyboard-alt) "␨")
(cl:define-symbol-macro keyboard-shift "␩")
(cl:setf (cl:symbol-value 'keyboard-shift) "␩")
(cl:define-symbol-macro keyboard-super "␪")
(cl:setf (cl:symbol-value 'keyboard-super) "␪")
(cl:define-symbol-macro keyboard-tab "␫")
(cl:setf (cl:symbol-value 'keyboard-tab) "␫")
(cl:define-symbol-macro keyboard-caps "␬")
(cl:setf (cl:symbol-value 'keyboard-caps) "␬")
(cl:define-symbol-macro keyboard-backspace "␭")
(cl:setf (cl:symbol-value 'keyboard-backspace) "␭")
(cl:define-symbol-macro keyboard-enter "␮")
(cl:setf (cl:symbol-value 'keyboard-enter) "␮")
(cl:define-symbol-macro keyboard-escape "␯")
(cl:setf (cl:symbol-value 'keyboard-escape) "␯")
(cl:define-symbol-macro keyboard-print-screen "␰")
(cl:setf (cl:symbol-value 'keyboard-print-screen) "␰")
(cl:define-symbol-macro keyboard-scroll-lock "␱")
(cl:setf (cl:symbol-value 'keyboard-scroll-lock) "␱")
(cl:define-symbol-macro keyboard-pause "␲")
(cl:setf (cl:symbol-value 'keyboard-pause) "␲")
(cl:define-symbol-macro keyboard-num-lock "␳")
(cl:setf (cl:symbol-value 'keyboard-num-lock) "␳")
(cl:define-symbol-macro keyboard-insert "␴")
(cl:setf (cl:symbol-value 'keyboard-insert) "␴")
(cl:define-symbol-macro keyboard-home "␵")
(cl:setf (cl:symbol-value 'keyboard-home) "␵")
(cl:define-symbol-macro keyboard-page-up "␶")
(cl:setf (cl:symbol-value 'keyboard-page-up) "␶")
(cl:define-symbol-macro keyboard-delete "␷")
(cl:setf (cl:symbol-value 'keyboard-delete) "␷")
(cl:define-symbol-macro keyboard-end "␸")
(cl:setf (cl:symbol-value 'keyboard-end) "␸")
(cl:define-symbol-macro keyboard-page-down "␹")
(cl:setf (cl:symbol-value 'keyboard-page-down) "␹")
(cl:define-symbol-macro keyboard-space "␺")
(cl:setf (cl:symbol-value 'keyboard-space) "␺")
(cl:define-symbol-macro key-empty-press "␻")
(cl:setf (cl:symbol-value 'key-empty-press) "␻")
(cl:define-symbol-macro device-gamepad "␼")
(cl:setf (cl:symbol-value 'device-gamepad) "␼")
(cl:define-symbol-macro device-keyboard "␽")
(cl:setf (cl:symbol-value 'device-keyboard) "␽")
(cl:define-symbol-macro device-mouse "␾")
(cl:setf (cl:symbol-value 'device-mouse) "␾")
(cl:define-symbol-macro device-mouse-keyboard "␿")
(cl:setf (cl:symbol-value 'device-mouse-keyboard) "␿")
(cl:define-symbol-macro device-ds4 "⑀")
(cl:setf (cl:symbol-value 'device-ds4) "⑀")
(cl:define-symbol-macro device-dualsense "⑁")
(cl:setf (cl:symbol-value 'device-dualsense) "⑁")
(cl:define-symbol-macro device-x360 "⑂")
(cl:setf (cl:symbol-value 'device-x360) "⑂")
(cl:define-symbol-macro device-numpad "⑃")
(cl:setf (cl:symbol-value 'device-numpad) "⑃")
(cl:define-symbol-macro keyboard-alt-gr "⑊")
(cl:setf (cl:symbol-value 'keyboard-alt-gr) "⑊")
(cl:define-symbol-macro keyboard-alt-l "⑋")
(cl:setf (cl:symbol-value 'keyboard-alt-l) "⑋")
(cl:define-symbol-macro keyboard-alt-r "⑌")
(cl:setf (cl:symbol-value 'keyboard-alt-r) "⑌")
(cl:define-symbol-macro keyboard-control-l "⑍")
(cl:setf (cl:symbol-value 'keyboard-control-l) "⑍")
(cl:define-symbol-macro keyboard-control-r "⑎")
(cl:setf (cl:symbol-value 'keyboard-control-r) "⑎")
(cl:define-symbol-macro keyboard-shift-l "⑏")
(cl:setf (cl:symbol-value 'keyboard-shift-l) "⑏")
(cl:define-symbol-macro keyboard-shift-r "⑐")
(cl:setf (cl:symbol-value 'keyboard-shift-r) "⑐")
(cl:define-symbol-macro keyboard-option "⑑")
(cl:setf (cl:symbol-value 'keyboard-option) "⑑")
(cl:define-symbol-macro keyboard-command "⑒")
(cl:setf (cl:symbol-value 'keyboard-command) "⑒")
(cl:define-symbol-macro keyboard-f1 "①")
(cl:setf (cl:symbol-value 'keyboard-f1) "①")
(cl:define-symbol-macro keyboard-f2 "②")
(cl:setf (cl:symbol-value 'keyboard-f2) "②")
(cl:define-symbol-macro keyboard-f3 "③")
(cl:setf (cl:symbol-value 'keyboard-f3) "③")
(cl:define-symbol-macro keyboard-f4 "④")
(cl:setf (cl:symbol-value 'keyboard-f4) "④")
(cl:define-symbol-macro keyboard-f5 "⑤")
(cl:setf (cl:symbol-value 'keyboard-f5) "⑤")
(cl:define-symbol-macro keyboard-f6 "⑥")
(cl:setf (cl:symbol-value 'keyboard-f6) "⑥")
(cl:define-symbol-macro keyboard-f7 "⑦")
(cl:setf (cl:symbol-value 'keyboard-f7) "⑦")
(cl:define-symbol-macro keyboard-f8 "⑧")
(cl:setf (cl:symbol-value 'keyboard-f8) "⑧")
(cl:define-symbol-macro keyboard-f9 "⑨")
(cl:setf (cl:symbol-value 'keyboard-f9) "⑨")
(cl:define-symbol-macro keyboard-f10 "⑩")
(cl:setf (cl:symbol-value 'keyboard-f10) "⑩")
(cl:define-symbol-macro keyboard-f11 "⑪")
(cl:setf (cl:symbol-value 'keyboard-f11) "⑪")
(cl:define-symbol-macro keyboard-f12 "⑫")
(cl:setf (cl:symbol-value 'keyboard-f12) "⑫")
(cl:define-symbol-macro keyboard-numpad-1 "⑴")
(cl:setf (cl:symbol-value 'keyboard-numpad-1) "⑴")
(cl:define-symbol-macro keyboard-numpad-2 "⑵")
(cl:setf (cl:symbol-value 'keyboard-numpad-2) "⑵")
(cl:define-symbol-macro keyboard-numpad-3 "⑶")
(cl:setf (cl:symbol-value 'keyboard-numpad-3) "⑶")
(cl:define-symbol-macro keyboard-numpad-4 "⑷")
(cl:setf (cl:symbol-value 'keyboard-numpad-4) "⑷")
(cl:define-symbol-macro keyboard-numpad-5 "⑸")
(cl:setf (cl:symbol-value 'keyboard-numpad-5) "⑸")
(cl:define-symbol-macro keyboard-numpad-6 "⑹")
(cl:setf (cl:symbol-value 'keyboard-numpad-6) "⑹")
(cl:define-symbol-macro keyboard-numpad-7 "⑺")
(cl:setf (cl:symbol-value 'keyboard-numpad-7) "⑺")
(cl:define-symbol-macro keyboard-numpad-8 "⑻")
(cl:setf (cl:symbol-value 'keyboard-numpad-8) "⑻")
(cl:define-symbol-macro keyboard-numpad-9 "⑼")
(cl:setf (cl:symbol-value 'keyboard-numpad-9) "⑼")
(cl:define-symbol-macro keyboard-numpad-0 "⑽")
(cl:setf (cl:symbol-value 'keyboard-numpad-0) "⑽")
(cl:define-symbol-macro keyboard-numpad-dot "⑾")
(cl:setf (cl:symbol-value 'keyboard-numpad-dot) "⑾")
(cl:define-symbol-macro keyboard-numpad-enter "⑿")
(cl:setf (cl:symbol-value 'keyboard-numpad-enter) "⑿")
(cl:define-symbol-macro keyboard-numpad-minus "⒀")
(cl:setf (cl:symbol-value 'keyboard-numpad-minus) "⒀")
(cl:define-symbol-macro keyboard-numpad-plus "⒁")
(cl:setf (cl:symbol-value 'keyboard-numpad-plus) "⒁")
(cl:define-symbol-macro keyboard-numpad-slash "⒂")
(cl:setf (cl:symbol-value 'keyboard-numpad-slash) "⒂")
(cl:define-symbol-macro keyboard-numpad-star "⒃")
(cl:setf (cl:symbol-value 'keyboard-numpad-star) "⒃")
(cl:define-symbol-macro keyboard-numpad-equals "⒄")
(cl:setf (cl:symbol-value 'keyboard-numpad-equals) "⒄")
(cl:define-symbol-macro keyboard-key "⒏")
(cl:setf (cl:symbol-value 'keyboard-key) "⒏")
(cl:define-symbol-macro icon-1 "⓵")
(cl:setf (cl:symbol-value 'icon-1) "⓵")
(cl:define-symbol-macro icon-2 "⓶")
(cl:setf (cl:symbol-value 'icon-2) "⓶")
(cl:define-symbol-macro icon-3 "⓷")
(cl:setf (cl:symbol-value 'icon-3) "⓷")
(cl:define-symbol-macro icon-4 "⓸")
(cl:setf (cl:symbol-value 'icon-4) "⓸")
(cl:define-symbol-macro icon-5 "⓹")
(cl:setf (cl:symbol-value 'icon-5) "⓹")
(cl:define-symbol-macro icon-6 "⓺")
(cl:setf (cl:symbol-value 'icon-6) "⓺")
(cl:define-symbol-macro icon-7 "⓻")
(cl:setf (cl:symbol-value 'icon-7) "⓻")
(cl:define-symbol-macro icon-8 "⓼")
(cl:setf (cl:symbol-value 'icon-8) "⓼")
(cl:define-symbol-macro icon-9 "⓽")
(cl:setf (cl:symbol-value 'icon-9) "⓽")
(cl:define-symbol-macro icon-0 "⓿")
(cl:setf (cl:symbol-value 'icon-0) "⓿")
(cl:define-symbol-macro box-drawing-light-horizontal "─")
(cl:setf (cl:symbol-value 'box-drawing-light-horizontal) "─")
(cl:define-symbol-macro box-drawing-heavy-horizontal "━")
(cl:setf (cl:symbol-value 'box-drawing-heavy-horizontal) "━")
(cl:define-symbol-macro box-drawing-light-vertical "│")
(cl:setf (cl:symbol-value 'box-drawing-light-vertical) "│")
(cl:define-symbol-macro box-drawing-heavy-vertical "┃")
(cl:setf (cl:symbol-value 'box-drawing-heavy-vertical) "┃")
(cl:define-symbol-macro box-drawing-light-triple-dash-horizontal "┄")
(cl:setf (cl:symbol-value 'box-drawing-light-triple-dash-horizontal) "┄")
(cl:define-symbol-macro box-drawing-heavy-triple-dash-horizontal "┅")
(cl:setf (cl:symbol-value 'box-drawing-heavy-triple-dash-horizontal) "┅")
(cl:define-symbol-macro box-drawing-light-triple-dash-vertical "┆")
(cl:setf (cl:symbol-value 'box-drawing-light-triple-dash-vertical) "┆")
(cl:define-symbol-macro box-drawing-heavy-triple-dash-vertical "┇")
(cl:setf (cl:symbol-value 'box-drawing-heavy-triple-dash-vertical) "┇")
(cl:define-symbol-macro box-drawing-light-quadruple-dash-horizontal "┈")
(cl:setf (cl:symbol-value 'box-drawing-light-quadruple-dash-horizontal) "┈")
(cl:define-symbol-macro box-drawing-heavy-quadruple-dash-horizontal "┉")
(cl:setf (cl:symbol-value 'box-drawing-heavy-quadruple-dash-horizontal) "┉")
(cl:define-symbol-macro box-drawing-light-quadruple-dash-vertical "┊")
(cl:setf (cl:symbol-value 'box-drawing-light-quadruple-dash-vertical) "┊")
(cl:define-symbol-macro box-drawing-heavy-quadruple-dash-vertical "┋")
(cl:setf (cl:symbol-value 'box-drawing-heavy-quadruple-dash-vertical) "┋")
(cl:define-symbol-macro box-drawing-light-down-and-right "┌")
(cl:setf (cl:symbol-value 'box-drawing-light-down-and-right) "┌")
(cl:define-symbol-macro box-drawing-down-light-and-right-heavy "┍")
(cl:setf (cl:symbol-value 'box-drawing-down-light-and-right-heavy) "┍")
(cl:define-symbol-macro box-drawing-down-heavy-and-right-light "┎")
(cl:setf (cl:symbol-value 'box-drawing-down-heavy-and-right-light) "┎")
(cl:define-symbol-macro box-drawing-heavy-down-and-right "┏")
(cl:setf (cl:symbol-value 'box-drawing-heavy-down-and-right) "┏")
(cl:define-symbol-macro box-drawing-light-down-and-left "┐")
(cl:setf (cl:symbol-value 'box-drawing-light-down-and-left) "┐")
(cl:define-symbol-macro box-drawing-down-light-and-left-heavy "┑")
(cl:setf (cl:symbol-value 'box-drawing-down-light-and-left-heavy) "┑")
(cl:define-symbol-macro box-drawing-down-heavy-and-left-light "┒")
(cl:setf (cl:symbol-value 'box-drawing-down-heavy-and-left-light) "┒")
(cl:define-symbol-macro box-drawing-heavy-down-and-left "┓")
(cl:setf (cl:symbol-value 'box-drawing-heavy-down-and-left) "┓")
(cl:define-symbol-macro box-drawing-light-up-and-right "└")
(cl:setf (cl:symbol-value 'box-drawing-light-up-and-right) "└")
(cl:define-symbol-macro box-drawing-up-light-and-right-heavy "┕")
(cl:setf (cl:symbol-value 'box-drawing-up-light-and-right-heavy) "┕")
(cl:define-symbol-macro box-drawing-up-heavy-and-right-light "┖")
(cl:setf (cl:symbol-value 'box-drawing-up-heavy-and-right-light) "┖")
(cl:define-symbol-macro box-drawing-heavy-up-and-right "┗")
(cl:setf (cl:symbol-value 'box-drawing-heavy-up-and-right) "┗")
(cl:define-symbol-macro box-drawing-light-up-and-left "┘")
(cl:setf (cl:symbol-value 'box-drawing-light-up-and-left) "┘")
(cl:define-symbol-macro box-drawing-up-light-and-left-heavy "┙")
(cl:setf (cl:symbol-value 'box-drawing-up-light-and-left-heavy) "┙")
(cl:define-symbol-macro box-drawing-up-heavy-and-left-light "┚")
(cl:setf (cl:symbol-value 'box-drawing-up-heavy-and-left-light) "┚")
(cl:define-symbol-macro box-drawing-heavy-up-and-left "┛")
(cl:setf (cl:symbol-value 'box-drawing-heavy-up-and-left) "┛")
(cl:define-symbol-macro box-drawing-light-vertical-and-right "├")
(cl:setf (cl:symbol-value 'box-drawing-light-vertical-and-right) "├")
(cl:define-symbol-macro box-drawing-vertical-light-and-right-heavy "┝")
(cl:setf (cl:symbol-value 'box-drawing-vertical-light-and-right-heavy) "┝")
(cl:define-symbol-macro box-drawing-up-heavy-and-right-down-light "┞")
(cl:setf (cl:symbol-value 'box-drawing-up-heavy-and-right-down-light) "┞")
(cl:define-symbol-macro box-drawing-down-heavy-and-right-up-light "┟")
(cl:setf (cl:symbol-value 'box-drawing-down-heavy-and-right-up-light) "┟")
(cl:define-symbol-macro box-drawing-vertical-heavy-and-right-light "┠")
(cl:setf (cl:symbol-value 'box-drawing-vertical-heavy-and-right-light) "┠")
(cl:define-symbol-macro box-drawing-down-light-and-right-up-heavy "┡")
(cl:setf (cl:symbol-value 'box-drawing-down-light-and-right-up-heavy) "┡")
(cl:define-symbol-macro box-drawing-up-light-and-right-down-heavy "┢")
(cl:setf (cl:symbol-value 'box-drawing-up-light-and-right-down-heavy) "┢")
(cl:define-symbol-macro box-drawing-heavy-vertical-and-right "┣")
(cl:setf (cl:symbol-value 'box-drawing-heavy-vertical-and-right) "┣")
(cl:define-symbol-macro box-drawing-light-vertical-and-left "┤")
(cl:setf (cl:symbol-value 'box-drawing-light-vertical-and-left) "┤")
(cl:define-symbol-macro box-drawing-vertical-light-and-left-heavy "┥")
(cl:setf (cl:symbol-value 'box-drawing-vertical-light-and-left-heavy) "┥")
(cl:define-symbol-macro box-drawing-up-heavy-and-left-down-light "┦")
(cl:setf (cl:symbol-value 'box-drawing-up-heavy-and-left-down-light) "┦")
(cl:define-symbol-macro box-drawing-down-heavy-and-left-up-light "┧")
(cl:setf (cl:symbol-value 'box-drawing-down-heavy-and-left-up-light) "┧")
(cl:define-symbol-macro box-drawing-vertical-heavy-and-left-light "┨")
(cl:setf (cl:symbol-value 'box-drawing-vertical-heavy-and-left-light) "┨")
(cl:define-symbol-macro box-drawing-down-light-and-left-up-heavy "┩")
(cl:setf (cl:symbol-value 'box-drawing-down-light-and-left-up-heavy) "┩")
(cl:define-symbol-macro box-drawing-up-light-and-left-down-heavy "┪")
(cl:setf (cl:symbol-value 'box-drawing-up-light-and-left-down-heavy) "┪")
(cl:define-symbol-macro box-drawing-heavy-vertical-and-left "┫")
(cl:setf (cl:symbol-value 'box-drawing-heavy-vertical-and-left) "┫")
(cl:define-symbol-macro box-drawing-light-down-and-horizontal "┬")
(cl:setf (cl:symbol-value 'box-drawing-light-down-and-horizontal) "┬")
(cl:define-symbol-macro box-drawing-left-heavy-and-right-down-light "┭")
(cl:setf (cl:symbol-value 'box-drawing-left-heavy-and-right-down-light) "┭")
(cl:define-symbol-macro box-drawing-right-heavy-and-left-down-light "┮")
(cl:setf (cl:symbol-value 'box-drawing-right-heavy-and-left-down-light) "┮")
(cl:define-symbol-macro box-drawing-down-light-and-horizontal-heavy "┯")
(cl:setf (cl:symbol-value 'box-drawing-down-light-and-horizontal-heavy) "┯")
(cl:define-symbol-macro box-drawing-down-heavy-and-horizontal-light "┰")
(cl:setf (cl:symbol-value 'box-drawing-down-heavy-and-horizontal-light) "┰")
(cl:define-symbol-macro box-drawing-right-light-and-left-down-heavy "┱")
(cl:setf (cl:symbol-value 'box-drawing-right-light-and-left-down-heavy) "┱")
(cl:define-symbol-macro box-drawing-left-light-and-right-down-heavy "┲")
(cl:setf (cl:symbol-value 'box-drawing-left-light-and-right-down-heavy) "┲")
(cl:define-symbol-macro box-drawing-heavy-down-and-horizontal "┳")
(cl:setf (cl:symbol-value 'box-drawing-heavy-down-and-horizontal) "┳")
(cl:define-symbol-macro box-drawing-light-up-and-horizontal "┴")
(cl:setf (cl:symbol-value 'box-drawing-light-up-and-horizontal) "┴")
(cl:define-symbol-macro box-drawing-left-heavy-and-right-up-light "┵")
(cl:setf (cl:symbol-value 'box-drawing-left-heavy-and-right-up-light) "┵")
(cl:define-symbol-macro box-drawing-right-heavy-and-left-up-light "┶")
(cl:setf (cl:symbol-value 'box-drawing-right-heavy-and-left-up-light) "┶")
(cl:define-symbol-macro box-drawing-up-light-and-horizontal-heavy "┷")
(cl:setf (cl:symbol-value 'box-drawing-up-light-and-horizontal-heavy) "┷")
(cl:define-symbol-macro box-drawing-up-heavy-and-horizontal-light "┸")
(cl:setf (cl:symbol-value 'box-drawing-up-heavy-and-horizontal-light) "┸")
(cl:define-symbol-macro box-drawing-right-light-and-left-up-heavy "┹")
(cl:setf (cl:symbol-value 'box-drawing-right-light-and-left-up-heavy) "┹")
(cl:define-symbol-macro box-drawing-left-light-and-right-up-heavy "┺")
(cl:setf (cl:symbol-value 'box-drawing-left-light-and-right-up-heavy) "┺")
(cl:define-symbol-macro box-drawing-heavy-up-and-horizontal "┻")
(cl:setf (cl:symbol-value 'box-drawing-heavy-up-and-horizontal) "┻")
(cl:define-symbol-macro box-drawing-light-vertical-and-horizontal "┼")
(cl:setf (cl:symbol-value 'box-drawing-light-vertical-and-horizontal) "┼")
(cl:define-symbol-macro box-drawing-left-heavy-and-right-vertical-light "┽")
(cl:setf (cl:symbol-value 'box-drawing-left-heavy-and-right-vertical-light) "┽")
(cl:define-symbol-macro box-drawing-right-heavy-and-left-vertical-light "┾")
(cl:setf (cl:symbol-value 'box-drawing-right-heavy-and-left-vertical-light) "┾")
(cl:define-symbol-macro box-drawing-vertical-light-and-horizontal-heavy "┿")
(cl:setf (cl:symbol-value 'box-drawing-vertical-light-and-horizontal-heavy) "┿")
(cl:define-symbol-macro box-drawing-up-heavy-and-down-horizontal-light "╀")
(cl:setf (cl:symbol-value 'box-drawing-up-heavy-and-down-horizontal-light) "╀")
(cl:define-symbol-macro box-drawing-down-heavy-and-up-horizontal-light "╁")
(cl:setf (cl:symbol-value 'box-drawing-down-heavy-and-up-horizontal-light) "╁")
(cl:define-symbol-macro box-drawing-vertical-heavy-and-horizontal-light "╂")
(cl:setf (cl:symbol-value 'box-drawing-vertical-heavy-and-horizontal-light) "╂")
(cl:define-symbol-macro box-drawing-left-up-heavy-and-right-down-light "╃")
(cl:setf (cl:symbol-value 'box-drawing-left-up-heavy-and-right-down-light) "╃")
(cl:define-symbol-macro box-drawing-right-up-heavy-and-left-down-light "╄")
(cl:setf (cl:symbol-value 'box-drawing-right-up-heavy-and-left-down-light) "╄")
(cl:define-symbol-macro box-drawing-left-down-heavy-and-right-up-light "╅")
(cl:setf (cl:symbol-value 'box-drawing-left-down-heavy-and-right-up-light) "╅")
(cl:define-symbol-macro box-drawing-right-down-heavy-and-left-up-light "╆")
(cl:setf (cl:symbol-value 'box-drawing-right-down-heavy-and-left-up-light) "╆")
(cl:define-symbol-macro box-drawing-down-light-and-up-horizontal-heavy "╇")
(cl:setf (cl:symbol-value 'box-drawing-down-light-and-up-horizontal-heavy) "╇")
(cl:define-symbol-macro box-drawing-up-light-and-down-horizontal-heavy "╈")
(cl:setf (cl:symbol-value 'box-drawing-up-light-and-down-horizontal-heavy) "╈")
(cl:define-symbol-macro box-drawing-right-light-and-left-vertical-heavy "╉")
(cl:setf (cl:symbol-value 'box-drawing-right-light-and-left-vertical-heavy) "╉")
(cl:define-symbol-macro box-drawing-left-light-and-right-vertical-heavy "╊")
(cl:setf (cl:symbol-value 'box-drawing-left-light-and-right-vertical-heavy) "╊")
(cl:define-symbol-macro box-drawing-heavy-vertical-and-horizontal "╋")
(cl:setf (cl:symbol-value 'box-drawing-heavy-vertical-and-horizontal) "╋")
(cl:define-symbol-macro box-drawing-light-double-dash-horizontal "╌")
(cl:setf (cl:symbol-value 'box-drawing-light-double-dash-horizontal) "╌")
(cl:define-symbol-macro box-drawing-heavy-double-dash-horizontal "╍")
(cl:setf (cl:symbol-value 'box-drawing-heavy-double-dash-horizontal) "╍")
(cl:define-symbol-macro box-drawing-light-double-dash-vertical "╎")
(cl:setf (cl:symbol-value 'box-drawing-light-double-dash-vertical) "╎")
(cl:define-symbol-macro box-drawing-heavy-double-dash-vertical "╏")
(cl:setf (cl:symbol-value 'box-drawing-heavy-double-dash-vertical) "╏")
(cl:define-symbol-macro box-drawing-light-diagonal-upper-right-to-lower-left "╱")
(cl:setf (cl:symbol-value 'box-drawing-light-diagonal-upper-right-to-lower-left) "╱")
(cl:define-symbol-macro box-drawing-light-diagonal-upper-left-to-lower-right "╲")
(cl:setf (cl:symbol-value 'box-drawing-light-diagonal-upper-left-to-lower-right) "╲")
(cl:define-symbol-macro box-drawing-light-diagonal-cross "╳")
(cl:setf (cl:symbol-value 'box-drawing-light-diagonal-cross) "╳")
(cl:define-symbol-macro box-drawing-light-left "╴")
(cl:setf (cl:symbol-value 'box-drawing-light-left) "╴")
(cl:define-symbol-macro box-drawing-light-up "╵")
(cl:setf (cl:symbol-value 'box-drawing-light-up) "╵")
(cl:define-symbol-macro box-drawing-light-right "╶")
(cl:setf (cl:symbol-value 'box-drawing-light-right) "╶")
(cl:define-symbol-macro box-drawing-light-down "╷")
(cl:setf (cl:symbol-value 'box-drawing-light-down) "╷")
(cl:define-symbol-macro box-drawing-heavy-left "╸")
(cl:setf (cl:symbol-value 'box-drawing-heavy-left) "╸")
(cl:define-symbol-macro box-drawing-heavy-up "╹")
(cl:setf (cl:symbol-value 'box-drawing-heavy-up) "╹")
(cl:define-symbol-macro box-drawing-heavy-right "╺")
(cl:setf (cl:symbol-value 'box-drawing-heavy-right) "╺")
(cl:define-symbol-macro box-drawing-heavy-down "╻")
(cl:setf (cl:symbol-value 'box-drawing-heavy-down) "╻")
(cl:define-symbol-macro box-drawing-light-left-and-heavy-right "╼")
(cl:setf (cl:symbol-value 'box-drawing-light-left-and-heavy-right) "╼")
(cl:define-symbol-macro box-drawing-light-up-and-heavy-down "╽")
(cl:setf (cl:symbol-value 'box-drawing-light-up-and-heavy-down) "╽")
(cl:define-symbol-macro box-drawing-heavy-left-and-light-right "╾")
(cl:setf (cl:symbol-value 'box-drawing-heavy-left-and-light-right) "╾")
(cl:define-symbol-macro box-drawing-heavy-up-and-light-down "╿")
(cl:setf (cl:symbol-value 'box-drawing-heavy-up-and-light-down) "╿")
(cl:define-symbol-macro box-drawing-upper-half-block "▀")
(cl:setf (cl:symbol-value 'box-drawing-upper-half-block) "▀")
(cl:define-symbol-macro box-drawing-lower-one-eighth-block "▁")
(cl:setf (cl:symbol-value 'box-drawing-lower-one-eighth-block) "▁")
(cl:define-symbol-macro box-drawing-lower-one-quarter-block "▂")
(cl:setf (cl:symbol-value 'box-drawing-lower-one-quarter-block) "▂")
(cl:define-symbol-macro box-drawing-lower-three-eighths-block "▃")
(cl:setf (cl:symbol-value 'box-drawing-lower-three-eighths-block) "▃")
(cl:define-symbol-macro box-drawing-lower-half-block "▄")
(cl:setf (cl:symbol-value 'box-drawing-lower-half-block) "▄")
(cl:define-symbol-macro box-drawing-lower-five-eighths-block "▅")
(cl:setf (cl:symbol-value 'box-drawing-lower-five-eighths-block) "▅")
(cl:define-symbol-macro box-drawing-lower-three-quarters-block "▆")
(cl:setf (cl:symbol-value 'box-drawing-lower-three-quarters-block) "▆")
(cl:define-symbol-macro box-drawing-lower-seven-eighths-block "▇")
(cl:setf (cl:symbol-value 'box-drawing-lower-seven-eighths-block) "▇")
(cl:define-symbol-macro box-drawing-full-block "█")
(cl:setf (cl:symbol-value 'box-drawing-full-block) "█")
(cl:define-symbol-macro box-drawing-left-seven-eighths-block "▉")
(cl:setf (cl:symbol-value 'box-drawing-left-seven-eighths-block) "▉")
(cl:define-symbol-macro box-drawing-left-three-quarters-block "▊")
(cl:setf (cl:symbol-value 'box-drawing-left-three-quarters-block) "▊")
(cl:define-symbol-macro box-drawing-left-five-eighths-block "▋")
(cl:setf (cl:symbol-value 'box-drawing-left-five-eighths-block) "▋")
(cl:define-symbol-macro box-drawing-left-half-block "▌")
(cl:setf (cl:symbol-value 'box-drawing-left-half-block) "▌")
(cl:define-symbol-macro box-drawing-left-three-eighths-block "▍")
(cl:setf (cl:symbol-value 'box-drawing-left-three-eighths-block) "▍")
(cl:define-symbol-macro box-drawing-left-one-quarter-block "▎")
(cl:setf (cl:symbol-value 'box-drawing-left-one-quarter-block) "▎")
(cl:define-symbol-macro box-drawing-left-one-eighth-block "▏")
(cl:setf (cl:symbol-value 'box-drawing-left-one-eighth-block) "▏")
(cl:define-symbol-macro box-drawing-right-half-block "▐")
(cl:setf (cl:symbol-value 'box-drawing-right-half-block) "▐")
(cl:define-symbol-macro box-drawing-light-shade "░")
(cl:setf (cl:symbol-value 'box-drawing-light-shade) "░")
(cl:define-symbol-macro box-drawing-medium-shade "▒")
(cl:setf (cl:symbol-value 'box-drawing-medium-shade) "▒")
(cl:define-symbol-macro box-drawing-dark-shade "▓")
(cl:setf (cl:symbol-value 'box-drawing-dark-shade) "▓")
(cl:define-symbol-macro box-drawing-upper-one-eighth-block "▔")
(cl:setf (cl:symbol-value 'box-drawing-upper-one-eighth-block) "▔")
(cl:define-symbol-macro box-drawing-right-one-eighth-block "▕")
(cl:setf (cl:symbol-value 'box-drawing-right-one-eighth-block) "▕")
(cl:define-symbol-macro box-drawing-quadrant-lower-left "▖")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-lower-left) "▖")
(cl:define-symbol-macro box-drawing-quadrant-lower-right "▗")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-lower-right) "▗")
(cl:define-symbol-macro box-drawing-quadrant-upper-left "▘")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-upper-left) "▘")
(cl:define-symbol-macro box-drawing-quadrant-upper-left-and-lower-left-and-lower-right "▙")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-upper-left-and-lower-left-and-lower-right) "▙")
(cl:define-symbol-macro box-drawing-quadrant-upper-left-and-lower-right "▚")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-upper-left-and-lower-right) "▚")
(cl:define-symbol-macro box-drawing-quadrant-upper-left-and-upper-right-and-lower-left "▛")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-upper-left-and-upper-right-and-lower-left) "▛")
(cl:define-symbol-macro box-drawing-quadrant-upper-left-and-upper-right-and-lower-right "▜")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-upper-left-and-upper-right-and-lower-right) "▜")
(cl:define-symbol-macro box-drawing-quadrant-upper-right "▝")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-upper-right) "▝")
(cl:define-symbol-macro box-drawing-quadrant-upper-right-and-lower-left "▞")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-upper-right-and-lower-left) "▞")
(cl:define-symbol-macro box-drawing-quadrant-upper-right-and-lower-left-and-lower-right "▟")
(cl:setf (cl:symbol-value 'box-drawing-quadrant-upper-right-and-lower-left-and-lower-right) "▟")
(cl:define-symbol-macro box-drawing-black-lower-right-triangle "◢")
(cl:setf (cl:symbol-value 'box-drawing-black-lower-right-triangle) "◢")
(cl:define-symbol-macro box-drawing-black-lower-left-triangle "◣")
(cl:setf (cl:symbol-value 'box-drawing-black-lower-left-triangle) "◣")
(cl:define-symbol-macro box-drawing-black-upper-left-triangle "◤")
(cl:setf (cl:symbol-value 'box-drawing-black-upper-left-triangle) "◤")
(cl:define-symbol-macro box-drawing-black-upper-right-triangle "◥")
(cl:setf (cl:symbol-value 'box-drawing-black-upper-right-triangle) "◥")
(cl:define-symbol-macro icon-sun "☀")
(cl:setf (cl:symbol-value 'icon-sun) "☀")
(cl:define-symbol-macro icon-star "★")
(cl:setf (cl:symbol-value 'icon-star) "★")
(cl:define-symbol-macro icon-empty-star "☆")
(cl:setf (cl:symbol-value 'icon-empty-star) "☆")
(cl:define-symbol-macro icon-checkbox "☐")
(cl:setf (cl:symbol-value 'icon-checkbox) "☐")
(cl:define-symbol-macro icon-checkbox-ticked "☑")
(cl:setf (cl:symbol-value 'icon-checkbox-ticked) "☑")
(cl:define-symbol-macro icon-checkbox-crossed "☒")
(cl:setf (cl:symbol-value 'icon-checkbox-crossed) "☒")
(cl:define-symbol-macro icon-skull "☠")
(cl:setf (cl:symbol-value 'icon-skull) "☠")
(cl:define-symbol-macro icon-warning-radioactive "☢")
(cl:setf (cl:symbol-value 'icon-warning-radioactive) "☢")
(cl:define-symbol-macro icon-warning-biohazard "☣")
(cl:setf (cl:symbol-value 'icon-warning-biohazard) "☣")
(cl:define-symbol-macro icon-frown "☹")
(cl:setf (cl:symbol-value 'icon-frown) "☹")
(cl:define-symbol-macro icon-smile "☺")
(cl:setf (cl:symbol-value 'icon-smile) "☺")
(cl:define-symbol-macro icon-sun-white "☼")
(cl:setf (cl:symbol-value 'icon-sun-white) "☼")
(cl:define-symbol-macro icon-gender-female "♀")
(cl:setf (cl:symbol-value 'icon-gender-female) "♀")
(cl:define-symbol-macro icon-gender-male "♂")
(cl:setf (cl:symbol-value 'icon-gender-male) "♂")
(cl:define-symbol-macro icon-full-spade "♠")
(cl:setf (cl:symbol-value 'icon-full-spade) "♠")
(cl:define-symbol-macro icon-empty-heart "♡")
(cl:setf (cl:symbol-value 'icon-empty-heart) "♡")
(cl:define-symbol-macro icon-empty-diamond "♢")
(cl:setf (cl:symbol-value 'icon-empty-diamond) "♢")
(cl:define-symbol-macro icon-full-club "♣")
(cl:setf (cl:symbol-value 'icon-full-club) "♣")
(cl:define-symbol-macro icon-empty-spade "♤")
(cl:setf (cl:symbol-value 'icon-empty-spade) "♤")
(cl:define-symbol-macro icon-full-heart "♥")
(cl:setf (cl:symbol-value 'icon-full-heart) "♥")
(cl:define-symbol-macro icon-full-diamond "♦")
(cl:setf (cl:symbol-value 'icon-full-diamond) "♦")
(cl:define-symbol-macro icon-empty-club "♧")
(cl:setf (cl:symbol-value 'icon-empty-club) "♧")
(cl:define-symbol-macro icon-d4 "♳")
(cl:setf (cl:symbol-value 'icon-d4) "♳")
(cl:define-symbol-macro icon-d6 "♴")
(cl:setf (cl:symbol-value 'icon-d6) "♴")
(cl:define-symbol-macro icon-d8 "♵")
(cl:setf (cl:symbol-value 'icon-d8) "♵")
(cl:define-symbol-macro icon-d10 "♶")
(cl:setf (cl:symbol-value 'icon-d10) "♶")
(cl:define-symbol-macro icon-d12 "♷")
(cl:setf (cl:symbol-value 'icon-d12) "♷")
(cl:define-symbol-macro icon-d20 "♸")
(cl:setf (cl:symbol-value 'icon-d20) "♸")
(cl:define-symbol-macro icon-d6-1 "⚀")
(cl:setf (cl:symbol-value 'icon-d6-1) "⚀")
(cl:define-symbol-macro icon-d6-2 "⚁")
(cl:setf (cl:symbol-value 'icon-d6-2) "⚁")
(cl:define-symbol-macro icon-d6-3 "⚂")
(cl:setf (cl:symbol-value 'icon-d6-3) "⚂")
(cl:define-symbol-macro icon-d6-4 "⚃")
(cl:setf (cl:symbol-value 'icon-d6-4) "⚃")
(cl:define-symbol-macro icon-d6-5 "⚄")
(cl:setf (cl:symbol-value 'icon-d6-5) "⚄")
(cl:define-symbol-macro icon-d6-6 "⚅")
(cl:setf (cl:symbol-value 'icon-d6-6) "⚅")
(cl:define-symbol-macro icon-flag "⚑")
(cl:setf (cl:symbol-value 'icon-flag) "⚑")
(cl:define-symbol-macro icon-gears "⚙")
(cl:setf (cl:symbol-value 'icon-gears) "⚙")
(cl:define-symbol-macro icon-warning-sign "⚠")
(cl:setf (cl:symbol-value 'icon-warning-sign) "⚠")
(cl:define-symbol-macro icon-sex-lesbian "⚢")
(cl:setf (cl:symbol-value 'icon-sex-lesbian) "⚢")
(cl:define-symbol-macro icon-sex-gay "⚣")
(cl:setf (cl:symbol-value 'icon-sex-gay) "⚣")
(cl:define-symbol-macro icon-sex-straight "⚤")
(cl:setf (cl:symbol-value 'icon-sex-straight) "⚤")
(cl:define-symbol-macro icon-gender-intersex "⚥")
(cl:setf (cl:symbol-value 'icon-gender-intersex) "⚥")
(cl:define-symbol-macro icon-gender-asexual "⚦")
(cl:setf (cl:symbol-value 'icon-gender-asexual) "⚦")
(cl:define-symbol-macro icon-gender-trans "⚧")
(cl:setf (cl:symbol-value 'icon-gender-trans) "⚧")
(cl:define-symbol-macro icon-gender-nonbinary "⚨")
(cl:setf (cl:symbol-value 'icon-gender-nonbinary) "⚨")
(cl:define-symbol-macro icon-sex-bisexual "⚩")
(cl:setf (cl:symbol-value 'icon-sex-bisexual) "⚩")
(cl:define-symbol-macro icon-sex-neuter "⚲")
(cl:setf (cl:symbol-value 'icon-sex-neuter) "⚲")
(cl:define-symbol-macro icon-stat-defense "⛨")
(cl:setf (cl:symbol-value 'icon-stat-defense) "⛨")
(cl:define-symbol-macro icon-scissors "✂")
(cl:setf (cl:symbol-value 'icon-scissors) "✂")
(cl:define-symbol-macro icon-tickmark "✔")
(cl:setf (cl:symbol-value 'icon-tickmark) "✔")
(cl:define-symbol-macro icon-cross "✗")
(cl:setf (cl:symbol-value 'icon-cross) "✗")
(cl:define-symbol-macro icon-crossmark "✘")
(cl:setf (cl:symbol-value 'icon-crossmark) "✘")
(cl:define-symbol-macro icon-spark "✦")
(cl:setf (cl:symbol-value 'icon-spark) "✦")
(cl:define-symbol-macro icon-question "❓")
(cl:setf (cl:symbol-value 'icon-question) "❓")
(cl:define-symbol-macro icon-bang "❗")
(cl:setf (cl:symbol-value 'icon-bang) "❗")
(cl:define-symbol-macro mouse-1 "➊")
(cl:setf (cl:symbol-value 'mouse-1) "➊")
(cl:define-symbol-macro mouse-2 "➋")
(cl:setf (cl:symbol-value 'mouse-2) "➋")
(cl:define-symbol-macro mouse-3 "➌")
(cl:setf (cl:symbol-value 'mouse-3) "➌")
(cl:define-symbol-macro mouse-4 "➍")
(cl:setf (cl:symbol-value 'mouse-4) "➍")
(cl:define-symbol-macro mouse-5 "➎")
(cl:setf (cl:symbol-value 'mouse-5) "➎")
(cl:define-symbol-macro mouse-6 "➏")
(cl:setf (cl:symbol-value 'mouse-6) "➏")
(cl:define-symbol-macro mouse-7 "➐")
(cl:setf (cl:symbol-value 'mouse-7) "➐")
(cl:define-symbol-macro mouse-8 "➑")
(cl:setf (cl:symbol-value 'mouse-8) "➑")
(cl:define-symbol-macro mouse-fill "➒")
(cl:setf (cl:symbol-value 'mouse-fill) "➒")
(cl:define-symbol-macro mouse-scroll-left "⟮")
(cl:setf (cl:symbol-value 'mouse-scroll-left) "⟮")
(cl:define-symbol-macro mouse-scroll-right "⟯")
(cl:setf (cl:symbol-value 'mouse-scroll-right) "⟯")
(cl:define-symbol-macro mouse-scroll-up "⟰")
(cl:setf (cl:symbol-value 'mouse-scroll-up) "⟰")
(cl:define-symbol-macro mouse-scroll-down "⟱")
(cl:setf (cl:symbol-value 'mouse-scroll-down) "⟱")
(cl:define-symbol-macro mouse-scroll-up-down "⟲")
(cl:setf (cl:symbol-value 'mouse-scroll-up-down) "⟲")
(cl:define-symbol-macro mouse-scroll-left-right "⟳")
(cl:setf (cl:symbol-value 'mouse-scroll-left-right) "⟳")
(cl:define-symbol-macro mouse-scroll-any "⟴")
(cl:setf (cl:symbol-value 'mouse-scroll-any) "⟴")
(cl:define-symbol-macro mouse-left "⟵")
(cl:setf (cl:symbol-value 'mouse-left) "⟵")
(cl:define-symbol-macro mouse-right "⟶")
(cl:setf (cl:symbol-value 'mouse-right) "⟶")
(cl:define-symbol-macro mouse-middle "⟷")
(cl:setf (cl:symbol-value 'mouse-middle) "⟷")
(cl:define-symbol-macro mouse-move-left "⟸")
(cl:setf (cl:symbol-value 'mouse-move-left) "⟸")
(cl:define-symbol-macro mouse-move-up "⟹")
(cl:setf (cl:symbol-value 'mouse-move-up) "⟹")
(cl:define-symbol-macro mouse-left-right "⟺")
(cl:setf (cl:symbol-value 'mouse-left-right) "⟺")
(cl:define-symbol-macro mouse-up-down "⟻")
(cl:setf (cl:symbol-value 'mouse-up-down) "⟻")
(cl:define-symbol-macro mouse-any "⟼")
(cl:setf (cl:symbol-value 'mouse-any) "⟼")
(cl:define-symbol-macro mouse-move-right "⟽")
(cl:setf (cl:symbol-value 'mouse-move-right) "⟽")
(cl:define-symbol-macro mouse-move-down "⟾")
(cl:setf (cl:symbol-value 'mouse-move-down) "⟾")
(cl:define-symbol-macro icon-box "⬛")
(cl:setf (cl:symbol-value 'icon-box) "⬛")
(cl:define-symbol-macro icon-resize-left "⭠")
(cl:setf (cl:symbol-value 'icon-resize-left) "⭠")
(cl:define-symbol-macro ican-expand-up "⭡")
(cl:setf (cl:symbol-value 'ican-expand-up) "⭡")
(cl:define-symbol-macro icon-resize-right "⭢")
(cl:setf (cl:symbol-value 'icon-resize-right) "⭢")
(cl:define-symbol-macro icon-resize-down "⭣")
(cl:setf (cl:symbol-value 'icon-resize-down) "⭣")
(cl:define-symbol-macro icon-resize-horizontal "⭤")
(cl:setf (cl:symbol-value 'icon-resize-horizontal) "⭤")
(cl:define-symbol-macro icon-resize-vertical "⭥")
(cl:setf (cl:symbol-value 'icon-resize-vertical) "⭥")
(cl:define-symbol-macro icon-resize-diagonal-down "⭦")
(cl:setf (cl:symbol-value 'icon-resize-diagonal-down) "⭦")
(cl:define-symbol-macro icon-resize-diagonal-up "⭧")
(cl:setf (cl:symbol-value 'icon-resize-diagonal-up) "⭧")
(cl:define-symbol-macro icon-resize-cardinal "⭨")
(cl:setf (cl:symbol-value 'icon-resize-cardinal) "⭨")
(cl:define-symbol-macro icon-resize-diagonal "⭩")
(cl:setf (cl:symbol-value 'icon-resize-diagonal) "⭩")
(cl:define-symbol-macro icon-redo "⭮")
(cl:setf (cl:symbol-value 'icon-redo) "⭮")
(cl:define-symbol-macro icon-undo "⭯")
(cl:setf (cl:symbol-value 'icon-undo) "⭯")
(cl:define-symbol-macro icon-paste "⭰")
(cl:setf (cl:symbol-value 'icon-paste) "⭰")
(cl:define-symbol-macro icon-upload "⭱")
(cl:setf (cl:symbol-value 'icon-upload) "⭱")
(cl:define-symbol-macro icon-copy "⭲")
(cl:setf (cl:symbol-value 'icon-copy) "⭲")
(cl:define-symbol-macro icon-download "⭳")
(cl:setf (cl:symbol-value 'icon-download) "⭳")
(cl:define-symbol-macro icon-playstation "")
(cl:setf (cl:symbol-value 'icon-playstation) "")
(cl:define-symbol-macro icon-xbox "")
(cl:setf (cl:symbol-value 'icon-xbox) "")
(cl:define-symbol-macro icon-nintendo-switch "")
(cl:setf (cl:symbol-value 'icon-nintendo-switch) "")
(cl:define-symbol-macro icon-ayaneo "")
(cl:setf (cl:symbol-value 'icon-ayaneo) "")
(cl:define-symbol-macro icon-lenovo-legion "")
(cl:setf (cl:symbol-value 'icon-lenovo-legion) "")
(cl:define-symbol-macro rog-ally-armoury "")
(cl:setf (cl:symbol-value 'rog-ally-armoury) "")
(cl:define-symbol-macro rog-ally-command "")
(cl:setf (cl:symbol-value 'rog-ally-command) "")
(cl:define-symbol-macro icon-mac "")
(cl:setf (cl:symbol-value 'icon-mac) "")
(cl:define-symbol-macro icon-windows "")
(cl:setf (cl:symbol-value 'icon-windows) "")
(cl:define-symbol-macro icon-linux "")
(cl:setf (cl:symbol-value 'icon-linux) "")
(cl:define-symbol-macro icon-bsd "")
(cl:setf (cl:symbol-value 'icon-bsd) "")
(cl:define-symbol-macro icon-steam "")
(cl:setf (cl:symbol-value 'icon-steam) "")
(cl:define-symbol-macro icon-itch-io "")
(cl:setf (cl:symbol-value 'icon-itch-io) "")
(cl:define-symbol-macro icon-humble "")
(cl:setf (cl:symbol-value 'icon-humble) "")
(cl:define-symbol-macro icon-epic-game-store "")
(cl:setf (cl:symbol-value 'icon-epic-game-store) "")
(cl:define-symbol-macro icon-good-old-games "")
(cl:setf (cl:symbol-value 'icon-good-old-games) "")
(cl:define-symbol-macro msi-claw-center "")
(cl:setf (cl:symbol-value 'msi-claw-center) "")
(cl:define-symbol-macro msi-claw-quick "")
(cl:setf (cl:symbol-value 'msi-claw-quick) "")
(cl:define-symbol-macro icon-meta "")
(cl:setf (cl:symbol-value 'icon-meta) "")
(cl:define-symbol-macro icon-shirakumo "")
(cl:setf (cl:symbol-value 'icon-shirakumo) "")
(cl:define-symbol-macro icon-trial "")
(cl:setf (cl:symbol-value 'icon-trial) "")
(cl:define-symbol-macro icon-unity "")
(cl:setf (cl:symbol-value 'icon-unity) "")
(cl:define-symbol-macro icon-godot "")
(cl:setf (cl:symbol-value 'icon-godot) "")
(cl:define-symbol-macro icon-gms "")
(cl:setf (cl:symbol-value 'icon-gms) "")
(cl:define-symbol-macro icon-unreal "")
(cl:setf (cl:symbol-value 'icon-unreal) "")
(cl:define-symbol-macro icon-love2d "")
(cl:setf (cl:symbol-value 'icon-love2d) "")
(cl:define-symbol-macro keyboard-zenkaku-hankaku "＀")
(cl:setf (cl:symbol-value 'keyboard-zenkaku-hankaku) "＀")
(cl:define-symbol-macro keyboard-exclamation "！")
(cl:setf (cl:symbol-value 'keyboard-exclamation) "！")
(cl:define-symbol-macro keyboard-doublequote "＂")
(cl:setf (cl:symbol-value 'keyboard-doublequote) "＂")
(cl:define-symbol-macro keyboard-pound "＃")
(cl:setf (cl:symbol-value 'keyboard-pound) "＃")
(cl:define-symbol-macro keyboard-dollar "＄")
(cl:setf (cl:symbol-value 'keyboard-dollar) "＄")
(cl:define-symbol-macro keyboard-percent "％")
(cl:setf (cl:symbol-value 'keyboard-percent) "％")
(cl:define-symbol-macro keyboard-ampersand "＆")
(cl:setf (cl:symbol-value 'keyboard-ampersand) "＆")
(cl:define-symbol-macro keyboard-quote "＇")
(cl:setf (cl:symbol-value 'keyboard-quote) "＇")
(cl:define-symbol-macro keyboard-open-parenthesis "（")
(cl:setf (cl:symbol-value 'keyboard-open-parenthesis) "（")
(cl:define-symbol-macro keyboard-close-parenthesis "）")
(cl:setf (cl:symbol-value 'keyboard-close-parenthesis) "）")
(cl:define-symbol-macro keyboard-star "＊")
(cl:setf (cl:symbol-value 'keyboard-star) "＊")
(cl:define-symbol-macro keyboard-plus "＋")
(cl:setf (cl:symbol-value 'keyboard-plus) "＋")
(cl:define-symbol-macro keyboard-comma "，")
(cl:setf (cl:symbol-value 'keyboard-comma) "，")
(cl:define-symbol-macro keyboard-dash "－")
(cl:setf (cl:symbol-value 'keyboard-dash) "－")
(cl:define-symbol-macro keyboard-period "．")
(cl:setf (cl:symbol-value 'keyboard-period) "．")
(cl:define-symbol-macro keyboard-slash "／")
(cl:setf (cl:symbol-value 'keyboard-slash) "／")
(cl:define-symbol-macro keyboard-0 "０")
(cl:setf (cl:symbol-value 'keyboard-0) "０")
(cl:define-symbol-macro keyboard-1 "１")
(cl:setf (cl:symbol-value 'keyboard-1) "１")
(cl:define-symbol-macro keyboard-2 "２")
(cl:setf (cl:symbol-value 'keyboard-2) "２")
(cl:define-symbol-macro keyboard-3 "３")
(cl:setf (cl:symbol-value 'keyboard-3) "３")
(cl:define-symbol-macro keyboard-4 "４")
(cl:setf (cl:symbol-value 'keyboard-4) "４")
(cl:define-symbol-macro keyboard-5 "５")
(cl:setf (cl:symbol-value 'keyboard-5) "５")
(cl:define-symbol-macro keyboard-6 "６")
(cl:setf (cl:symbol-value 'keyboard-6) "６")
(cl:define-symbol-macro keyboard-7 "７")
(cl:setf (cl:symbol-value 'keyboard-7) "７")
(cl:define-symbol-macro keyboard-8 "８")
(cl:setf (cl:symbol-value 'keyboard-8) "８")
(cl:define-symbol-macro keyboard-9 "９")
(cl:setf (cl:symbol-value 'keyboard-9) "９")
(cl:define-symbol-macro keyboard-colon "：")
(cl:setf (cl:symbol-value 'keyboard-colon) "：")
(cl:define-symbol-macro keyboard-semicolon "；")
(cl:setf (cl:symbol-value 'keyboard-semicolon) "；")
(cl:define-symbol-macro keyboard-open-caret "＜")
(cl:setf (cl:symbol-value 'keyboard-open-caret) "＜")
(cl:define-symbol-macro keyboard-equals "＝")
(cl:setf (cl:symbol-value 'keyboard-equals) "＝")
(cl:define-symbol-macro keyboard-close-caret "＞")
(cl:setf (cl:symbol-value 'keyboard-close-caret) "＞")
(cl:define-symbol-macro keyboard-question-mark "？")
(cl:setf (cl:symbol-value 'keyboard-question-mark) "？")
(cl:define-symbol-macro keyboard-at "＠")
(cl:setf (cl:symbol-value 'keyboard-at) "＠")
(cl:define-symbol-macro keyboard-a "Ａ")
(cl:setf (cl:symbol-value 'keyboard-a) "Ａ")
(cl:define-symbol-macro keyboard-b "Ｂ")
(cl:setf (cl:symbol-value 'keyboard-b) "Ｂ")
(cl:define-symbol-macro keyboard-c "Ｃ")
(cl:setf (cl:symbol-value 'keyboard-c) "Ｃ")
(cl:define-symbol-macro keyboard-d "Ｄ")
(cl:setf (cl:symbol-value 'keyboard-d) "Ｄ")
(cl:define-symbol-macro keyboard-e "Ｅ")
(cl:setf (cl:symbol-value 'keyboard-e) "Ｅ")
(cl:define-symbol-macro keyboard-f "Ｆ")
(cl:setf (cl:symbol-value 'keyboard-f) "Ｆ")
(cl:define-symbol-macro keyboard-g "Ｇ")
(cl:setf (cl:symbol-value 'keyboard-g) "Ｇ")
(cl:define-symbol-macro keyboard-h "Ｈ")
(cl:setf (cl:symbol-value 'keyboard-h) "Ｈ")
(cl:define-symbol-macro keyboard-i "Ｉ")
(cl:setf (cl:symbol-value 'keyboard-i) "Ｉ")
(cl:define-symbol-macro keyboard-j "Ｊ")
(cl:setf (cl:symbol-value 'keyboard-j) "Ｊ")
(cl:define-symbol-macro keyboard-k "Ｋ")
(cl:setf (cl:symbol-value 'keyboard-k) "Ｋ")
(cl:define-symbol-macro keyboard-l "Ｌ")
(cl:setf (cl:symbol-value 'keyboard-l) "Ｌ")
(cl:define-symbol-macro keyboard-m "Ｍ")
(cl:setf (cl:symbol-value 'keyboard-m) "Ｍ")
(cl:define-symbol-macro keyboard-n "Ｎ")
(cl:setf (cl:symbol-value 'keyboard-n) "Ｎ")
(cl:define-symbol-macro keyboard-o "Ｏ")
(cl:setf (cl:symbol-value 'keyboard-o) "Ｏ")
(cl:define-symbol-macro keyboard-p "Ｐ")
(cl:setf (cl:symbol-value 'keyboard-p) "Ｐ")
(cl:define-symbol-macro keyboard-q "Ｑ")
(cl:setf (cl:symbol-value 'keyboard-q) "Ｑ")
(cl:define-symbol-macro keyboard-r "Ｒ")
(cl:setf (cl:symbol-value 'keyboard-r) "Ｒ")
(cl:define-symbol-macro keyboard-s "Ｓ")
(cl:setf (cl:symbol-value 'keyboard-s) "Ｓ")
(cl:define-symbol-macro keyboard-t "Ｔ")
(cl:setf (cl:symbol-value 'keyboard-t) "Ｔ")
(cl:define-symbol-macro keyboard-u "Ｕ")
(cl:setf (cl:symbol-value 'keyboard-u) "Ｕ")
(cl:define-symbol-macro keyboard-v "Ｖ")
(cl:setf (cl:symbol-value 'keyboard-v) "Ｖ")
(cl:define-symbol-macro keyboard-w "Ｗ")
(cl:setf (cl:symbol-value 'keyboard-w) "Ｗ")
(cl:define-symbol-macro keyboard-x "Ｘ")
(cl:setf (cl:symbol-value 'keyboard-x) "Ｘ")
(cl:define-symbol-macro keyboard-y "Ｙ")
(cl:setf (cl:symbol-value 'keyboard-y) "Ｙ")
(cl:define-symbol-macro keyboard-z "Ｚ")
(cl:setf (cl:symbol-value 'keyboard-z) "Ｚ")
(cl:define-symbol-macro keyboard-open-bracket "［")
(cl:setf (cl:symbol-value 'keyboard-open-bracket) "［")
(cl:define-symbol-macro keyboard-backslash "＼")
(cl:setf (cl:symbol-value 'keyboard-backslash) "＼")
(cl:define-symbol-macro keyboard-close-bracket "］")
(cl:setf (cl:symbol-value 'keyboard-close-bracket) "］")
(cl:define-symbol-macro keyboard-caret "＾")
(cl:setf (cl:symbol-value 'keyboard-caret) "＾")
(cl:define-symbol-macro keyboard-underscore "＿")
(cl:setf (cl:symbol-value 'keyboard-underscore) "＿")
(cl:define-symbol-macro keyboard-backtick "｀")
(cl:setf (cl:symbol-value 'keyboard-backtick) "｀")
(cl:define-symbol-macro keyboard-a-diaeresis "ａ")
(cl:setf (cl:symbol-value 'keyboard-a-diaeresis) "ａ")
(cl:define-symbol-macro keyboard-a-grave "ｂ")
(cl:setf (cl:symbol-value 'keyboard-a-grave) "ｂ")
(cl:define-symbol-macro keyboard-cedille "ｃ")
(cl:setf (cl:symbol-value 'keyboard-cedille) "ｃ")
(cl:define-symbol-macro keyboard-e-acute "ｅ")
(cl:setf (cl:symbol-value 'keyboard-e-acute) "ｅ")
(cl:define-symbol-macro keyboard-e-grave "ｆ")
(cl:setf (cl:symbol-value 'keyboard-e-grave) "ｆ")
(cl:define-symbol-macro keyboard-o-diaeresis "ｏ")
(cl:setf (cl:symbol-value 'keyboard-o-diaeresis) "ｏ")
(cl:define-symbol-macro keyboard-u-diaeresis "ｕ")
(cl:setf (cl:symbol-value 'keyboard-u-diaeresis) "ｕ")
(cl:define-symbol-macro keyboard-u-grave "ｖ")
(cl:setf (cl:symbol-value 'keyboard-u-grave) "ｖ")
(cl:define-symbol-macro keyboard-open-brace "｛")
(cl:setf (cl:symbol-value 'keyboard-open-brace) "｛")
(cl:define-symbol-macro keyboard-bar "｜")
(cl:setf (cl:symbol-value 'keyboard-bar) "｜")
(cl:define-symbol-macro keyboard-close-brace "｝")
(cl:setf (cl:symbol-value 'keyboard-close-brace) "｝")
(cl:define-symbol-macro keyboard-tilde "～")
(cl:setf (cl:symbol-value 'keyboard-tilde) "～")
(cl:define-symbol-macro keyboard-kana "ｶ")
(cl:setf (cl:symbol-value 'keyboard-kana) "ｶ")
(cl:define-symbol-macro keyboard-henkan "ﾍ")
(cl:setf (cl:symbol-value 'keyboard-henkan) "ﾍ")
(cl:define-symbol-macro keyboard-muhekan "ﾏ")
(cl:setf (cl:symbol-value 'keyboard-muhekan) "ﾏ")
(cl:define-symbol-macro keyboard-backfill "ﾠ")
(cl:setf (cl:symbol-value 'keyboard-backfill) "ﾠ")
(cl:define-symbol-macro icon-bone-broken "𓄯")
(cl:setf (cl:symbol-value 'icon-bone-broken) "𓄯")
(cl:define-symbol-macro icon-italic "𝘪")
(cl:setf (cl:symbol-value 'icon-italic) "𝘪")
(cl:define-symbol-macro icon-bold "𝝖")
(cl:setf (cl:symbol-value 'icon-bold) "𝝖")
(cl:define-symbol-macro icon-stat-psychic "🌀")
(cl:setf (cl:symbol-value 'icon-stat-psychic) "🌀")
(cl:define-symbol-macro icon-water "🌊")
(cl:setf (cl:symbol-value 'icon-water) "🌊")
(cl:define-symbol-macro icon-moon-new "🌑")
(cl:setf (cl:symbol-value 'icon-moon-new) "🌑")
(cl:define-symbol-macro icon-moon-crescent-waxing "🌒")
(cl:setf (cl:symbol-value 'icon-moon-crescent-waxing) "🌒")
(cl:define-symbol-macro icon-moon-quarter-first "🌓")
(cl:setf (cl:symbol-value 'icon-moon-quarter-first) "🌓")
(cl:define-symbol-macro icon-moon-gibbous-waxing "🌔")
(cl:setf (cl:symbol-value 'icon-moon-gibbous-waxing) "🌔")
(cl:define-symbol-macro icon-moon-full "🌕")
(cl:setf (cl:symbol-value 'icon-moon-full) "🌕")
(cl:define-symbol-macro icon-moon-gibbous-waning "🌖")
(cl:setf (cl:symbol-value 'icon-moon-gibbous-waning) "🌖")
(cl:define-symbol-macro icon-moon-quarter-last "🌗")
(cl:setf (cl:symbol-value 'icon-moon-quarter-last) "🌗")
(cl:define-symbol-macro icon-moon-crescent-waning "🌘")
(cl:setf (cl:symbol-value 'icon-moon-crescent-waning) "🌘")
(cl:define-symbol-macro icon-moon "🌙")
(cl:setf (cl:symbol-value 'icon-moon) "🌙")
(cl:define-symbol-macro icon-stat-dark "🌚")
(cl:setf (cl:symbol-value 'icon-stat-dark) "🌚")
(cl:define-symbol-macro icon-weather-sunny "🌣")
(cl:setf (cl:symbol-value 'icon-weather-sunny) "🌣")
(cl:define-symbol-macro icon-weather-cloudy "🌤")
(cl:setf (cl:symbol-value 'icon-weather-cloudy) "🌤")
(cl:define-symbol-macro icon-weather-overcast "🌥")
(cl:setf (cl:symbol-value 'icon-weather-overcast) "🌥")
(cl:define-symbol-macro icon-weather-rainy "🌦")
(cl:setf (cl:symbol-value 'icon-weather-rainy) "🌦")
(cl:define-symbol-macro icon-weather-rain "🌧")
(cl:setf (cl:symbol-value 'icon-weather-rain) "🌧")
(cl:define-symbol-macro icon-weather-snow "🌨")
(cl:setf (cl:symbol-value 'icon-weather-snow) "🌨")
(cl:define-symbol-macro icon-lightning "🌩")
(cl:setf (cl:symbol-value 'icon-lightning) "🌩")
(cl:define-symbol-macro icon-wind "🌬")
(cl:setf (cl:symbol-value 'icon-wind) "🌬")
(cl:define-symbol-macro icon-item "🍲")
(cl:setf (cl:symbol-value 'icon-item) "🍲")
(cl:define-symbol-macro icon-microphone "🎤")
(cl:setf (cl:symbol-value 'icon-microphone) "🎤")
(cl:define-symbol-macro icon-headphones "🎧")
(cl:setf (cl:symbol-value 'icon-headphones) "🎧")
(cl:define-symbol-macro icon-music "🎶")
(cl:setf (cl:symbol-value 'icon-music) "🎶")
(cl:define-symbol-macro icon-action-run "🏃")
(cl:setf (cl:symbol-value 'icon-action-run) "🏃")
(cl:define-symbol-macro icon-stat-speed "🏎")
(cl:setf (cl:symbol-value 'icon-stat-speed) "🏎")
(cl:define-symbol-macro icon-stat-piercing "🏹")
(cl:setf (cl:symbol-value 'icon-stat-piercing) "🏹")
(cl:define-symbol-macro icon-fish "🐟")
(cl:setf (cl:symbol-value 'icon-fish) "🐟")
(cl:define-symbol-macro icon-eye "👁")
(cl:setf (cl:symbol-value 'icon-eye) "👁")
(cl:define-symbol-macro icon-point-up "👆")
(cl:setf (cl:symbol-value 'icon-point-up) "👆")
(cl:define-symbol-macro icon-point-down "👇")
(cl:setf (cl:symbol-value 'icon-point-down) "👇")
(cl:define-symbol-macro icon-point-left "👈")
(cl:setf (cl:symbol-value 'icon-point-left) "👈")
(cl:define-symbol-macro icon-point-right "👉")
(cl:setf (cl:symbol-value 'icon-point-right) "👉")
(cl:define-symbol-macro icon-stat-bludgeoning "👊")
(cl:setf (cl:symbol-value 'icon-stat-bludgeoning) "👊")
(cl:define-symbol-macro icon-thumbs-up "👍")
(cl:setf (cl:symbol-value 'icon-thumbs-up) "👍")
(cl:define-symbol-macro icon-thumbs-down "👎")
(cl:setf (cl:symbol-value 'icon-thumbs-down) "👎")
(cl:define-symbol-macro icon-stat-poison "💀")
(cl:setf (cl:symbol-value 'icon-stat-poison) "💀")
(cl:define-symbol-macro device-dance-pad "💃")
(cl:setf (cl:symbol-value 'device-dance-pad) "💃")
(cl:define-symbol-macro icon-stat-acid "💧")
(cl:setf (cl:symbol-value 'icon-stat-acid) "💧")
(cl:define-symbol-macro icon-stat-strength "💪")
(cl:setf (cl:symbol-value 'icon-stat-strength) "💪")
(cl:define-symbol-macro icon-bubble-speech "💬")
(cl:setf (cl:symbol-value 'icon-bubble-speech) "💬")
(cl:define-symbol-macro icon-money-bag "💰")
(cl:setf (cl:symbol-value 'icon-money-bag) "💰")
(cl:define-symbol-macro icon-laptop "💻")
(cl:setf (cl:symbol-value 'icon-laptop) "💻")
(cl:define-symbol-macro icon-diskette "💾")
(cl:setf (cl:symbol-value 'icon-diskette) "💾")
(cl:define-symbol-macro icon-optical-disc "💿")
(cl:setf (cl:symbol-value 'icon-optical-disc) "💿")
(cl:define-symbol-macro icon-file-folder "📁")
(cl:setf (cl:symbol-value 'icon-file-folder) "📁")
(cl:define-symbol-macro icon-file-folder-open "📂")
(cl:setf (cl:symbol-value 'icon-file-folder-open) "📂")
(cl:define-symbol-macro icon-clipboard "📋")
(cl:setf (cl:symbol-value 'icon-clipboard) "📋")
(cl:define-symbol-macro icon-code "📜")
(cl:setf (cl:symbol-value 'icon-code) "📜")
(cl:define-symbol-macro icon-write "📝")
(cl:setf (cl:symbol-value 'icon-write) "📝")
(cl:define-symbol-macro icon-console "📟")
(cl:setf (cl:symbol-value 'icon-console) "📟")
(cl:define-symbol-macro device-phone "📱")
(cl:setf (cl:symbol-value 'device-phone) "📱")
(cl:define-symbol-macro icon-reception-good "📶")
(cl:setf (cl:symbol-value 'icon-reception-good) "📶")
(cl:define-symbol-macro icon-webcam "📷")
(cl:setf (cl:symbol-value 'icon-webcam) "📷")
(cl:define-symbol-macro icon-warning-flashing "📸")
(cl:setf (cl:symbol-value 'icon-warning-flashing) "📸")
(cl:define-symbol-macro icon-camera "📹")
(cl:setf (cl:symbol-value 'icon-camera) "📹")
(cl:define-symbol-macro icon-speaker "📾")
(cl:setf (cl:symbol-value 'icon-speaker) "📾")
(cl:define-symbol-macro icon-shuffle "🔀")
(cl:setf (cl:symbol-value 'icon-shuffle) "🔀")
(cl:define-symbol-macro icon-loop "🔁")
(cl:setf (cl:symbol-value 'icon-loop) "🔁")
(cl:define-symbol-macro icon-loop-once "🔂")
(cl:setf (cl:symbol-value 'icon-loop-once) "🔂")
(cl:define-symbol-macro icon-brightness-low "🔅")
(cl:setf (cl:symbol-value 'icon-brightness-low) "🔅")
(cl:define-symbol-macro icon-brightness-high "🔆")
(cl:setf (cl:symbol-value 'icon-brightness-high) "🔆")
(cl:define-symbol-macro icon-volume-muted "🔇")
(cl:setf (cl:symbol-value 'icon-volume-muted) "🔇")
(cl:define-symbol-macro icon-volume-quiet "🔈")
(cl:setf (cl:symbol-value 'icon-volume-quiet) "🔈")
(cl:define-symbol-macro icon-volume-medium "🔉")
(cl:setf (cl:symbol-value 'icon-volume-medium) "🔉")
(cl:define-symbol-macro icon-volume-loud "🔊")
(cl:setf (cl:symbol-value 'icon-volume-loud) "🔊")
(cl:define-symbol-macro icon-battery-full "🔋")
(cl:setf (cl:symbol-value 'icon-battery-full) "🔋")
(cl:define-symbol-macro icon-electrical-plug "🔌")
(cl:setf (cl:symbol-value 'icon-electrical-plug) "🔌")
(cl:define-symbol-macro icon-magnifying-glass "🔍")
(cl:setf (cl:symbol-value 'icon-magnifying-glass) "🔍")
(cl:define-symbol-macro icon-magnifying-glass-right "🔎")
(cl:setf (cl:symbol-value 'icon-magnifying-glass-right) "🔎")
(cl:define-symbol-macro icon-key "🔑")
(cl:setf (cl:symbol-value 'icon-key) "🔑")
(cl:define-symbol-macro icon-lock "🔒")
(cl:setf (cl:symbol-value 'icon-lock) "🔒")
(cl:define-symbol-macro icon-lock-open "🔓")
(cl:setf (cl:symbol-value 'icon-lock-open) "🔓")
(cl:define-symbol-macro icon-bell "🔔")
(cl:setf (cl:symbol-value 'icon-bell) "🔔")
(cl:define-symbol-macro icon-bell-muted "🔕")
(cl:setf (cl:symbol-value 'icon-bell-muted) "🔕")
(cl:define-symbol-macro icon-rating-18 "🔞")
(cl:setf (cl:symbol-value 'icon-rating-18) "🔞")
(cl:define-symbol-macro icon-fire "🔥")
(cl:setf (cl:symbol-value 'icon-fire) "🔥")
(cl:define-symbol-macro icon-stat-light "🔦")
(cl:setf (cl:symbol-value 'icon-stat-light) "🔦")
(cl:define-symbol-macro icon-action-attack "🔪")
(cl:setf (cl:symbol-value 'icon-action-attack) "🔪")
(cl:define-symbol-macro device-light-gun "🔫")
(cl:setf (cl:symbol-value 'device-light-gun) "🔫")
(cl:define-symbol-macro icon-microphone-muted "🕨")
(cl:setf (cl:symbol-value 'icon-microphone-muted) "🕨")
(cl:define-symbol-macro icon-noise "🕬")
(cl:setf (cl:symbol-value 'icon-noise) "🕬")
(cl:define-symbol-macro icon-network-ping "🕭")
(cl:setf (cl:symbol-value 'icon-network-ping) "🕭")
(cl:define-symbol-macro icon-crossbones "🕱")
(cl:setf (cl:symbol-value 'icon-crossbones) "🕱")
(cl:define-symbol-macro icon-warning-phobia "🕷")
(cl:setf (cl:symbol-value 'icon-warning-phobia) "🕷")
(cl:define-symbol-macro device-steering-wheel "🕸")
(cl:setf (cl:symbol-value 'device-steering-wheel) "🕸")
(cl:define-symbol-macro device-joy-stick "🕹")
(cl:setf (cl:symbol-value 'device-joy-stick) "🕹")
(cl:define-symbol-macro device-vr-headset "🕻")
(cl:setf (cl:symbol-value 'device-vr-headset) "🕻")
(cl:define-symbol-macro device-vr-controller "🕼")
(cl:setf (cl:symbol-value 'device-vr-controller) "🕼")
(cl:define-symbol-macro device-flight-stick "🕽")
(cl:setf (cl:symbol-value 'device-flight-stick) "🕽")
(cl:define-symbol-macro icon-network-connected "🕾")
(cl:setf (cl:symbol-value 'icon-network-connected) "🕾")
(cl:define-symbol-macro icon-network-connecting "🕿")
(cl:setf (cl:symbol-value 'icon-network-connecting) "🕿")
(cl:define-symbol-macro icon-network-disconnected "🖀")
(cl:setf (cl:symbol-value 'icon-network-disconnected) "🖀")
(cl:define-symbol-macro icon-network-wired "🖇")
(cl:setf (cl:symbol-value 'icon-network-wired) "🖇")
(cl:define-symbol-macro icon-underline "🖉")
(cl:setf (cl:symbol-value 'icon-underline) "🖉")
(cl:define-symbol-macro icon-strikethrough "🖊")
(cl:setf (cl:symbol-value 'icon-strikethrough) "🖊")
(cl:define-symbol-macro icon-supertext "🖋")
(cl:setf (cl:symbol-value 'icon-supertext) "🖋")
(cl:define-symbol-macro icon-subtext "🖌")
(cl:setf (cl:symbol-value 'icon-subtext) "🖌")
(cl:define-symbol-macro icon-foreground "🖍")
(cl:setf (cl:symbol-value 'icon-foreground) "🖍")
(cl:define-symbol-macro icon-background "🖎")
(cl:setf (cl:symbol-value 'icon-background) "🖎")
(cl:define-symbol-macro icon-stat-health "🖤")
(cl:setf (cl:symbol-value 'icon-stat-health) "🖤")
(cl:define-symbol-macro icon-processor "🖥")
(cl:setf (cl:symbol-value 'icon-processor) "🖥")
(cl:define-symbol-macro icon-internet "🖧")
(cl:setf (cl:symbol-value 'icon-internet) "🖧")
(cl:define-symbol-macro icon-graphics-card "🖨")
(cl:setf (cl:symbol-value 'icon-graphics-card) "🖨")
(cl:define-symbol-macro icon-memory "🖪")
(cl:setf (cl:symbol-value 'icon-memory) "🖪")
(cl:define-symbol-macro icon-usb-stick "🖫")
(cl:setf (cl:symbol-value 'icon-usb-stick) "🖫")
(cl:define-symbol-macro icon-database "🖬")
(cl:setf (cl:symbol-value 'icon-database) "🖬")
(cl:define-symbol-macro icon-hard-disk "🖴")
(cl:setf (cl:symbol-value 'icon-hard-disk) "🖴")
(cl:define-symbol-macro icon-screen "🖵")
(cl:setf (cl:symbol-value 'icon-screen) "🖵")
(cl:define-symbol-macro icon-text-entry "🖹")
(cl:setf (cl:symbol-value 'icon-text-entry) "🖹")
(cl:define-symbol-macro icon-image "🖼")
(cl:setf (cl:symbol-value 'icon-image) "🖼")
(cl:define-symbol-macro icon-window-minimize "🗕")
(cl:setf (cl:symbol-value 'icon-window-minimize) "🗕")
(cl:define-symbol-macro icon-window-maximize "🗖")
(cl:setf (cl:symbol-value 'icon-window-maximize) "🗖")
(cl:define-symbol-macro icon-window-overlap "🗗")
(cl:setf (cl:symbol-value 'icon-window-overlap) "🗗")
(cl:define-symbol-macro icon-window-close "🗙")
(cl:setf (cl:symbol-value 'icon-window-close) "🗙")
(cl:define-symbol-macro icon-size-increase "🗚")
(cl:setf (cl:symbol-value 'icon-size-increase) "🗚")
(cl:define-symbol-macro icon-size-decrease "🗛")
(cl:setf (cl:symbol-value 'icon-size-decrease) "🗛")
(cl:define-symbol-macro icon-stat-slashing "🗡")
(cl:setf (cl:symbol-value 'icon-stat-slashing) "🗡")
(cl:define-symbol-macro icon-speak "🗣")
(cl:setf (cl:symbol-value 'icon-speak) "🗣")
(cl:define-symbol-macro icon-bubble-speech-right "🗨")
(cl:setf (cl:symbol-value 'icon-bubble-speech-right) "🗨")
(cl:define-symbol-macro icon-language "🗩")
(cl:setf (cl:symbol-value 'icon-language) "🗩")
(cl:define-symbol-macro icon-bubble-speech-two "🗪")
(cl:setf (cl:symbol-value 'icon-bubble-speech-two) "🗪")
(cl:define-symbol-macro icon-bubble-speech-three "🗫")
(cl:setf (cl:symbol-value 'icon-bubble-speech-three) "🗫")
(cl:define-symbol-macro icon-bubble-thought-right "🗬")
(cl:setf (cl:symbol-value 'icon-bubble-thought-right) "🗬")
(cl:define-symbol-macro icon-bubble-thought "🗭")
(cl:setf (cl:symbol-value 'icon-bubble-thought) "🗭")
(cl:define-symbol-macro icon-bubble-scream-right "🗮")
(cl:setf (cl:symbol-value 'icon-bubble-scream-right) "🗮")
(cl:define-symbol-macro icon-bubble-scream "🗯")
(cl:setf (cl:symbol-value 'icon-bubble-scream) "🗯")
(cl:define-symbol-macro icon-warning-swearing "🗱")
(cl:setf (cl:symbol-value 'icon-warning-swearing) "🗱")
(cl:define-symbol-macro icon-warning-photosensitivity "🗲")
(cl:setf (cl:symbol-value 'icon-warning-photosensitivity) "🗲")
(cl:define-symbol-macro icon-map "🗺")
(cl:setf (cl:symbol-value 'icon-map) "🗺")
(cl:define-symbol-macro icon-battery-charging "🙐")
(cl:setf (cl:symbol-value 'icon-battery-charging) "🙐")
(cl:define-symbol-macro icon-battery-medium "🙑")
(cl:setf (cl:symbol-value 'icon-battery-medium) "🙑")
(cl:define-symbol-macro icon-battery-empty "🙒")
(cl:setf (cl:symbol-value 'icon-battery-empty) "🙒")
(cl:define-symbol-macro icon-reception-bad "🙓")
(cl:setf (cl:symbol-value 'icon-reception-bad) "🙓")
(cl:define-symbol-macro icon-reception-medium "🙔")
(cl:setf (cl:symbol-value 'icon-reception-medium) "🙔")
(cl:define-symbol-macro icon-rating-0 "🙕")
(cl:setf (cl:symbol-value 'icon-rating-0) "🙕")
(cl:define-symbol-macro icon-rating-3 "🙖")
(cl:setf (cl:symbol-value 'icon-rating-3) "🙖")
(cl:define-symbol-macro icon-rating-6 "🙗")
(cl:setf (cl:symbol-value 'icon-rating-6) "🙗")
(cl:define-symbol-macro icon-rating-9 "🙘")
(cl:setf (cl:symbol-value 'icon-rating-9) "🙘")
(cl:define-symbol-macro icon-rating-12 "🙙")
(cl:setf (cl:symbol-value 'icon-rating-12) "🙙")
(cl:define-symbol-macro icon-rating-16 "🙚")
(cl:setf (cl:symbol-value 'icon-rating-16) "🙚")
(cl:define-symbol-macro icon-rating-21 "🙛")
(cl:setf (cl:symbol-value 'icon-rating-21) "🙛")
(cl:define-symbol-macro icon-exit "🚪")
(cl:setf (cl:symbol-value 'icon-exit) "🚪")
(cl:define-symbol-macro icon-denied "🛇")
(cl:setf (cl:symbol-value 'icon-denied) "🛇")
(cl:define-symbol-macro icon-information "🛈")
(cl:setf (cl:symbol-value 'icon-information) "🛈")
(cl:define-symbol-macro icon-shopping-cart "🛒")
(cl:setf (cl:symbol-value 'icon-shopping-cart) "🛒")
(cl:define-symbol-macro icon-network-wireless "🛜")
(cl:setf (cl:symbol-value 'icon-network-wireless) "🛜")
(cl:define-symbol-macro icon-action-defend "🛡")
(cl:setf (cl:symbol-value 'icon-action-defend) "🛡")
(cl:define-symbol-macro icon-aperture "🞉")
(cl:setf (cl:symbol-value 'icon-aperture) "🞉")
(cl:define-symbol-macro icon-bone "🦴")
(cl:setf (cl:symbol-value 'icon-bone) "🦴")
(cl:define-symbol-macro icon-ice "🧊")
(cl:setf (cl:symbol-value 'icon-ice) "🧊")
(cl:define-symbol-macro icon-accessory "🧣")
(cl:setf (cl:symbol-value 'icon-accessory) "🧣")
(cl:define-symbol-macro icon-armor "🧥")
(cl:setf (cl:symbol-value 'icon-armor) "🧥")
(cl:define-symbol-macro icon-compass "🧭")
(cl:setf (cl:symbol-value 'icon-compass) "🧭")
(cl:define-symbol-macro icon-stat-magic "🪄")
(cl:setf (cl:symbol-value 'icon-stat-magic) "🪄")
(cl:define-symbol-macro icon-weapon "🪓")
(cl:setf (cl:symbol-value 'icon-weapon) "🪓")
(cl:define-symbol-macro icon-earth "🪨")
(cl:setf (cl:symbol-value 'icon-earth) "🪨")
(cl:define-symbol-macro box-drawing-upper-and-right-and-lower-triangular-three-quarters-block "🭨")
(cl:setf (cl:symbol-value 'box-drawing-upper-and-right-and-lower-triangular-three-quarters-block) "🭨")
(cl:define-symbol-macro box-drawing-left-and-lower-and-right-triangular-three-quarters-block "🭩")
(cl:setf (cl:symbol-value 'box-drawing-left-and-lower-and-right-triangular-three-quarters-block) "🭩")
(cl:define-symbol-macro box-drawing-upper-and-left-and-lower-triangular-three-quarters-block "🭪")
(cl:setf (cl:symbol-value 'box-drawing-upper-and-left-and-lower-triangular-three-quarters-block) "🭪")
(cl:define-symbol-macro box-drawing-left-and-upper-and-right-triangular-three-quarters-block "🭫")
(cl:setf (cl:symbol-value 'box-drawing-left-and-upper-and-right-triangular-three-quarters-block) "🭫")
(cl:define-symbol-macro box-drawing-left-triangular-one-quarter-block "🭬")
(cl:setf (cl:symbol-value 'box-drawing-left-triangular-one-quarter-block) "🭬")
(cl:define-symbol-macro box-drawing-upper-triangular-one-quarter-block "🭭")
(cl:setf (cl:symbol-value 'box-drawing-upper-triangular-one-quarter-block) "🭭")
(cl:define-symbol-macro box-drawing-right-triangular-one-quarter-block "🭮")
(cl:setf (cl:symbol-value 'box-drawing-right-triangular-one-quarter-block) "🭮")
(cl:define-symbol-macro box-drawing-lower-triangular-one-quarter-block "🭯")
(cl:setf (cl:symbol-value 'box-drawing-lower-triangular-one-quarter-block) "🭯")
(cl:define-symbol-macro box-drawing-upper-one-quarter-block "🮂")
(cl:setf (cl:symbol-value 'box-drawing-upper-one-quarter-block) "🮂")
(cl:define-symbol-macro box-drawing-upper-three-eighths-block "🮃")
(cl:setf (cl:symbol-value 'box-drawing-upper-three-eighths-block) "🮃")
(cl:define-symbol-macro box-drawing-upper-five-eighths-block "🮄")
(cl:setf (cl:symbol-value 'box-drawing-upper-five-eighths-block) "🮄")
(cl:define-symbol-macro box-drawing-upper-three-quarters-block "🮅")
(cl:setf (cl:symbol-value 'box-drawing-upper-three-quarters-block) "🮅")
(cl:define-symbol-macro box-drawing-upper-seven-eighths-block "🮆")
(cl:setf (cl:symbol-value 'box-drawing-upper-seven-eighths-block) "🮆")
(cl:define-symbol-macro box-drawing-right-one-quarter-block "🮇")
(cl:setf (cl:symbol-value 'box-drawing-right-one-quarter-block) "🮇")
(cl:define-symbol-macro box-drawing-right-three-eighths-block "🮈")
(cl:setf (cl:symbol-value 'box-drawing-right-three-eighths-block) "🮈")
(cl:define-symbol-macro box-drawing-right-five-eighths-block "🮉")
(cl:setf (cl:symbol-value 'box-drawing-right-five-eighths-block) "🮉")
(cl:define-symbol-macro box-drawing-right-three-quarters-block "🮊")
(cl:setf (cl:symbol-value 'box-drawing-right-three-quarters-block) "🮊")
(cl:define-symbol-macro box-drawing-right-seven-eighths-block "🮋")
(cl:setf (cl:symbol-value 'box-drawing-right-seven-eighths-block) "🮋")

(cl:defun get (get)
  (cl:etypecase get
    (cl:symbol (get (cl:symbol-name get)))
    (cl:string (cl:symbol-value (cl:find-symbol get #.cl:*package*)))))
(cl:do-symbols (cl:symbol cl:*package*)
  (cl:export cl:symbol))
